### ISSUE TITLE
Issues with staging slots and deploy from GitHub

### ISSUE THREAD

**Issue by ThatRendle** [projectkudu/kudu#1124]
So, I've just added staging slots to a bunch of (i.e. 10) Azure Websites, some new, some that have been in production for months, which previously had deployment from GitHub set up. When I added the staging slots, I disconnected the production slots from source control, because I didn't want them deploying on pushes as well. And now I'm having major problems with the deployment from GitHub, which I'm thinking might be related to disparity between the keys in the staging slot and those in the production.

If I disconnect and reconnect the staging slots to source control, then they fetch and deploy the latest commit successfully.

But then after I swap them with the production slots, the next time I do a `git push`, the deploy hook fails. I checked the Webhooks & Services tab in GitHub and every post received a 403 error. I've checked the webhook URL in the staging site's configuration page and it matches the one that GitHub has. 

When I try to do a manual sync using the button in the portal, the fetch fails with a `Permission denied (publickey)` error.

Have I messed something up somewhere, and if so, how can I fix it? :(

**Comment by neusamir** [comment]
We are seeing issues with this and have a similar setup to what @markrendle has. We have an azure web app with a pre production slot. It is hooked up to the master branch of a github repo. The deploy command is sent out but 50% of the time the autoswap fails. It doesn't seem to be consistently broken every other time. Sometimes it fails two times in a row. To fix it, we just update the master branch and that kicks off a new build and that usually fixes it. We don't swap via the portal (although that would work). 

This is the error we get:

```
<step title="POST /operations/autoswap?slot=production&amp;operationId=AUTOSWAPce25aabe-d981-412d-bf47-ff440bf9613f, x-ms-request-id: d440ee48-f7d1-4b11-be10-f4dfdf33ecc2" date="2016-06-23T22:09:15.918" >
	<step title="Response: NotFound" date="2016-06-23T22:09:20.005" /><!-- duration: 0ms -->
</step><!-- duration: 4097ms -->
<step title="Error occurred" date="2016-06-23T22:09:20.053" type="error" text="One or more errors occurred." stackTrace="   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass18_1.&lt;PerformBackgroundDeployment&gt;b__2()
	at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout)
	at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout)
	at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass18_0.&lt;PerformBackgroundDeployment&gt;b__1()" innerText="Response status code does not indicate success: 404 (Not Found)." innerStackTrace="   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
	at Kudu.Core.Infrastructure.OperationClient.&lt;PostAsync&gt;d__7`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Kudu.Core.Deployment.AutoSwapHandler.&lt;HandleAutoSwap&gt;d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__12.MoveNext()" /><!-- duration: 0ms -->
</step><!-- duration: 286964ms -->
```

I can provide logs and more details if you need them.

**Comment by davidebbo** [comment]
@shrimpy any thought on this auto-swap issue?

@neusamir it may be best to open a new issue, as it's probably not exactly the same as the original, which was addressed.

**Comment by neusamir** [comment]
Ok sure, will do.

**Comment by shrimpy** [comment]
interestingly request for autoswap returns "404". @neusamir when you create your new issue, will be good if you can provide your site name directly or indirectly (https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) so that I can dig a bit more into your request.

```
    <step title="Response: NotFound" date="2016-06-23T22:09:20.005" /><!-- duration: 0ms -->

```
