### ISSUE TITLE
Can't use PhantomJS in a Web Job

### ISSUE THREAD

**Issue by morgs32** [projectkudu/kudu#1194]
Node modules "node-phantom" or "node-phantom-simple" don't appear to work in a Web Job.

Here is an example app.js:

```
var phantom = require('node-phantom-simple');
var fs = require('fs-extra');

var fetcher = {};

fetcher.fetchTimeline = function (url) {

  phantom.create(function(err,ph) {
    if (err)
      console.log(err);

    ph.createPage(function(err,page) {

      console.log("Opening " + url);

      page.viewportSize = { width: 740 };

      page.open(url, function(err,status) {
        if ('fail' === status) {
          console.log("Failed to get " + url);
        } else {

          page.evaluate(function() {

            var html = document.documentElement.outerHTML;

            return html;
          }, function(err,result) {
            if (err)
              console.log(err);
            else
              fs.writeFile("page.html", result, function(err) {
                if(err) {
                    console.log(err);
                } else {
                    console.log("The file was saved!");
                }
              });
          });
        }
      });
    });
  });
};

fetcher.fetchTimeline("http://www.google.com");
```

so, if you npm install on these dependencies:

```
        "node-phantom-simple": "~1.2.0",
        "fs-extra": "~0.9.1",
```

and zip it up. you should see this in the web job log:

```
[06/03/2014 13:28:06 > cbd536: SYS INFO] Status changed to Initializing
[06/03/2014 13:28:13 > cbd536: SYS INFO] Run script 'app.js' with script host - 'NodeScriptHost'
[06/03/2014 13:28:13 > cbd536: SYS INFO] Status changed to Running
[06/03/2014 13:28:13 > cbd536: ERR ] TypeError: Cannot call method 'createPage' of undefined
[06/03/2014 13:28:13 > cbd536: INFO] { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
[06/03/2014 13:28:13 > cbd536: ERR ]     at C:\DWASFiles\Sites\collegeitinerary\Temp\jobs\triggered\phantom\ogj4tlk1.mnm\app.js:13:8
[06/03/2014 13:28:13 > cbd536: ERR ]     at C:\DWASFiles\Sites\collegeitinerary\Temp\jobs\triggered\phantom\ogj4tlk1.mnm\node_modules\node-phantom-simple\node-phantom-simple.js:203:20
[06/03/2014 13:28:13 > cbd536: ERR ]     at ChildProcess.<anonymous> (C:\DWASFiles\Sites\collegeitinerary\Temp\jobs\triggered\phantom\ogj4tlk1.mnm\node_modules\node-phantom-simple\node-phantom-simple.js:93:10)
[06/03/2014 13:28:13 > cbd536: ERR ]     at ChildProcess.g (events.js:175:14)
[06/03/2014 13:28:13 > cbd536: ERR ]     at ChildProcess.EventEmitter.emit (events.js:95:17)
[06/03/2014 13:28:13 > cbd536: ERR ]     at Process.ChildProcess._handle.onexit (child_process.js:782:12)
[06/03/2014 13:28:14 > cbd536: SYS INFO] Status changed to Failed
[06/03/2014 13:28:14 > cbd536: SYS ERR ] Job failed due to exit code 1
```

**Comment by thEpisode** [comment]
3 year later and we haven't PhantomJS!! 😢
