### ISSUE TITLE
Misleading error message when .deployment file points to .sln file

### ISSUE THREAD

**Issue by alastairs** [projectkudu/kudu#121]
I'm trying to deploy a web application contained in a repository that also contains a large number of other projects and solutions.  I have added a .deployment file to the repository, which has the following contents:

```
[config]
project = path/to/WebApp.sln
```

Whenever I push to Kudu, I get the following output:

```
S:\code [branch]> git push http://localhost:38361/foo.git HEAD:master
Counting objects: 1095, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (222/222), done.
Writing objects: 100% (1003/1003), 140.43 KiB, done.
Total 1003 (delta 876), reused 888 (delta 780)
remote: New deployment received.
remote: Updating branch 'master'.
remote: Preparing deployment for commit id 'cc924c7e35'.
remote: Exception has been thrown by the target of an invocation.
remote:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
remote:    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
remote:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
remote:    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
remote:    at Kudu.Core.Infrastructure.VsSolution.EnsureProjects() in S:\personal\kudu\Kudu.Core\Infrastructure\VsSolution.cs:line 65
remote:    at Kudu.Core.Infrastructure.VsSolution.get_Projects() in S:\personal\kudu\Kudu.Core\Infrastructure\VsSolution.cs:line 41
remote:    at Kudu.Core.Infrastructure.VsHelper.ExistsInSolution(VsSolution solution, String targetPath) in S:\personal\kudu\Kudu.Core\Infrastructure\VsHelper.cs:line 75
remote:    at Kudu.Core.Infrastructure.VsHelper.<>c__DisplayClass3.<FindContainingSolutions>b__2(VsSolution solution) in S:\personal\kudu\Kudu.Core\Infrastructure\VsHelper.cs:line 31
remote:    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
remote:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
remote:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
remote:    at Kudu.Core.Infrastructure.VsHelper.FindContainingSolutions(String searchPath, String targetPath) in S:\personal\kudu\Kudu.Core\Infrastructure\VsHelper.cs:line 30
remote:    at Kudu.Core.Deployment.SiteBuilderFactory.ResolveProject(String repositoryRoot, String targetPath, Boolean tryWebSiteProject, SearchOption searchOption, Boolean specificConfiguration) in S:\personal\kudu\Kudu.Core\Dremote: t\SiteBuilderFactory.cs:line 129
remote:    at Kudu.Core.Deployment.SiteBuilderFactory.CreateBuilder(ITracer tracer, ILogger logger) in S:\personal\kudu\Kudu.Core\Deployment\SiteBuilderFactory.cs:line 43
remote:    at Kudu.Core.Deployment.DeploymentManager.Build(String id, ITracer tracer, IDisposable deployStep) in S:\personal\kudu\Kudu.Core\Deployment\DeploymentManager.cs:line 399
remote: Error - Changes committed to remote repository but your website not updated.
To http://localhost:38361/foo.git
   76b7c76..cc924c7  HEAD -> master
```

Initially, I set the project path to point directly at the web project as stated [here](https://github.com/projectkudu/kudu/wiki/Customizing-deployments), but then changed it on a hunch: the code is failing in `SolutionParser.ParseSolution()`, and figured that would be correct if it was passed a project file!  Unfortunately it's still failing even now I've pointed it at a solution file, so it's obviously something else.  

I can't work out how to debug the problem any further. When I run Kudu from Visual Studio, and attach to the IIS worker process for the Kudu application I'm trying to deploy, none of my breakpoints ever get hit.  The breakpoints are a solid red ball, indicating that symbols have been loaded for the class I'm trying to debug, and this only happens after I attach to the IIS worker process.

**Comment by mathiassiig** [comment]
Sorry for the bump, but I'm getting:

`The specified project 'MyProjectHere.csproj' is not valid. It needs to point to either a csproj/vbproj file or to a directory.`

Maybe the error could be more verbose.
