### ISSUE TITLE
Reduce noise in logfiles\eventlog.xml for FetchHandler.ProcessRequestAsync exception

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1395]
Looking at one customer eventlog.xml, I noticed many entries of below.  Issue aside, I think we should try to reduce noises in eventlog.xml.  One suggestion is not let exception propagated up to ASP.NET layer.  This can be achieve by try/catch exception and return Internal Server Error with message.   

``` xml
<Event>
  <System>
    <Provider Name="ASP.NET 4.0.30319.0"/>
    <EventID>1309</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>Keywords</Keywords>
    <TimeCreated SystemTime="2014-10-20T23:02:26Z"/>
    <EventRecordID>-1548570515</EventRecordID>
    <Channel>Application</Channel>
    <Computer>RD00155D44226D</Computer>
    <Security/>
  </System>
  <EventData>
    <Data>3005</Data>
    <Data>An unhandled exception has occurred.</Data>
    <Data>10/20/2014 11:02:26 PM</Data>
    <Data>10/20/2014 11:02:26 PM</Data>
    <Data>f7c8f418f70d4dd6b1aacda011786b83</Data>
    <Data>10</Data>
    <Data>1</Data>
    <Data>0</Data>
    <Data>/LM/W3SVC/2056889496/ROOT-1-130583193137951875</Data>
    <Data>Full</Data>
    <Data>/</Data>
    <Data>D:\Program Files (x86)\SiteExtensions\Kudu\28.31006.1184\</Data>
    <Data>RD00155D44226D</Data>
    <Data/>
    <Data>2216</Data>
    <Data>w3wp.exe</Data>
    <Data>IIS APPPOOL\anovia-io__fb33</Data>
    <Data>CommandLineException</Data>
    <Data>      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x860000, BaseAddress 0x9D0000, RegionSize 0x10000, State 0x2000
    D:\Program Files (x86)\Git\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

    D:\Program Files (x86)\Git\bin\git.exe fetch external --progress
       at Kudu.Core.Infrastructure.Executable.Execute(ITracer tracer, String arguments, Object[] args)
       at Kudu.Core.SourceControl.Git.GitExeRepository.&lt;&gt;c__DisplayClass4.&lt;FetchWithoutConflict&gt;b__0()
       at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
       at Kudu.Core.SourceControl.Git.GitExeRepository.GitFetchWithRetry[T](Func`1 func)
       at Kudu.Core.SourceControl.Git.GitExeRepository.FetchWithoutConflict(String remote, String branchName)
       at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger)
       at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__e.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass3.&lt;&lt;ProcessRequestAsync&gt;b__0&gt;d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Contracts.Infrastructure.LockExtensions.&lt;TryLockOperationAsync&gt;d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
       at System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)

    </Data>
    <Data>https://anovia-io-dev.scm.azurewebsites.net:443/deploy?scmType=GitHub</Data>
    <Data>/deploy</Data>
    <Data>192.30.252.47</Data>
    <Data>False</Data>
    <Data/>
    <Data>IIS APPPOOL\anovia-io__fb33</Data>
    <Data>6</Data>
    <Data>IIS APPPOOL\anovia-io__fb33</Data>
    <Data>False</Data>
    <Data>   at Kudu.Core.Infrastructure.Executable.Execute(ITracer tracer, String arguments, Object[] args)
       at Kudu.Core.SourceControl.Git.GitExeRepository.&lt;&gt;c__DisplayClass4.&lt;FetchWithoutConflict&gt;b__0()
       at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
       at Kudu.Core.SourceControl.Git.GitExeRepository.GitFetchWithRetry[T](Func`1 func)
       at Kudu.Core.SourceControl.Git.GitExeRepository.FetchWithoutConflict(String remote, String branchName)
       at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger)
       at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__e.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass3.&lt;&lt;ProcessRequestAsync&gt;b__0&gt;d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Contracts.Infrastructure.LockExtensions.&lt;TryLockOperationAsync&gt;d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
       at System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
    </Data>
  </EventData>
</Event>
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
