### ISSUE TITLE
Deployment on Azure generates error, "Web Deploy cannot modify the file 'bson.node' on the destination because it is locked by an external process."

### ISSUE THREAD

**Issue by johnwp** [projectkudu/kudu#1442]
I received the following error on deploying my node project on Azure: 

**Exception Message: Web Deploy cannot modify the file 'bson.node' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.**

Manually stopping the server before building seems to allow deployment to work (most of the time). However, adding `<EnableMSDeployAppOffline>true</EnableMSDeployAppOffline>` to pubxml doesn't seem to have any effect.

This error began appearing after installing connect-mongo. I haven't seen this problem in a similarly-configured Azure/MongoDB/Mongoose environment (sans connect-mongo).

How could I prevent this error?
Thanks in advance.

    Exception Message: Web Deploy cannot modify the file 'bson.node' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.
     Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE. (type DeploymentDetailedException)
    Exception Stack Trace: 
    Server stack trace: 
      at Microsoft.Web.Deployment.PackageSerializer.CheckForErrorOrCancel()
      at Microsoft.Web.Deployment.PackageSerializer.SerializePayload(DeploymentObject obj, Int32 objectId)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenDepthFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenSyncFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenSyncFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.PackageSerializer.SerializeChildrenSyncFirst(SerializeObjectContext objectContext)
      at Microsoft.Web.Deployment.AgentClientProvider.RemoteDestSync(DeploymentObject sourceObject, DeploymentSyncContext syncContext, Nullable`1 syncPass, String syncSessionId)
      at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
      at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
      at Microsoft.TeamFoundation.Deployment.Workflow.Activities.MSDeployWorker.RunCommandInternal(String publishEndpoint, String targetSite, String userName, String password, String packagePath, String setParametersPath, Boolean allowUntrustedCertificates, Boolean doNotDelete)
      at Microsoft.TeamFoundation.Deployment.Workflow.Activities.MSDeployWorker.RunCommand(String publishEndpoint, String targetSite, String userName, String password, String packagePath, String setParametersPath, Boolean allowUntrustedCertificates, Boolean doNotDelete)
      at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
      at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

    Exception rethrown at [0]: 
      at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
      at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData& msgData)
      at System.Action`8.EndInvoke(IAsyncResult result)
      at Microsoft.TeamFoundation.Deployment.Workflow.Activities.MSDeployWorker.EndExecute(AsyncCodeActivityContext context, IAsyncResult result)
      at System.Activities.AsyncCodeActivity.CompleteAsyncCodeActivityData.CompleteAsyncCodeActivityWorkItem.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)

**Comment by davidebbo** [comment]
Can you please post to the [Websites forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead? WebDeploy is not related to Project Kudu. Thanks!
