### ISSUE TITLE
"Illegal characters in path" when trying to deploy on Azure via Github

### ISSUE THREAD

**Issue by JakobOlsen** [projectkudu/kudu#1537]
When i push changes to Github, and Azure tries to deploy - I get an "unknown error" in Azure.

Digging in to the log file shows me, that it is an issue with Kudu.
Logfile:

```
<step title="Incoming Request" date="2015-04-17T10:08:51.176" instance="90d06e" url="/api/deployments/e781d28c2ddd94d2bc4965c4cba71d789dc3134d" method="PUT" type="request" pid="3884,2,6" Connection="Keep-Alive" Content-Length="0" Content-Type="text/plain; charset=utf-8" Accept="application/json" Accept-Language="en-US" Host="skirmish4242.scm.azurewebsites.net" User-Agent="Azure-Portal/5.3.00298.2" x-ms-client-request-id="c2fae4b2-dca4-4f5e-84d5-0398aeef22f0-2015-04-17 10:10:33Z" x-ms-client-session-id="6188c4a4-91da-4f96-9cdb-1c6ec452c1f9" X-SITE-DEPLOYMENT-ID="Skirmish4242" X-MS-WAWS-JWT="" >
  <step title="DeploymentService.Deploy(id)" date="2015-04-17T10:08:51.285" >
    <step title="Executing external process" date="2015-04-17T10:08:51.333" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 93ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-17T10:08:51.426" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-17T10:08:51.794" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 729ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-17T10:08:52.524" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-17T10:08:52.540" type="process" path="git.exe" arguments="log -n 1 e781d28c2ddd94d2bc4965c4cba71d789dc3134d --" /><!-- duration: 250ms -->
    <step title="DeploymentManager.Deploy(id)" date="2015-04-17T10:08:52.805" >
      <step title="Collecting changeset information" date="2015-04-17T10:08:52.836" /><!-- duration: 94ms -->
      <step title="Updating to specific changeset" date="2015-04-17T10:08:52.977" >
        <step title="Executing external process" date="2015-04-17T10:08:53.071" type="process" path="git.exe" arguments="checkout e781d28c2ddd94d2bc4965c4cba71d789dc3134d --force" /><!-- duration: 792ms -->
      </step><!-- duration: 901ms -->
      <step title="Updating submodules" date="2015-04-17T10:08:53.878" /><!-- duration: 67ms -->
      <step title="Determining deployment builder" date="2015-04-17T10:08:54.102" >
        <step title="Executing external process" date="2015-04-17T10:08:54.133" type="process" path="git.exe" arguments="ls-files *.csproj *.vbproj *.fsproj *.sln" /><!-- duration: 47ms -->
        <step title="Builder is WapBuilder" date="2015-04-17T10:08:54.227" /><!-- duration: 19ms -->
      </step><!-- duration: 156ms -->
    </step><!-- duration: 1512ms -->
    <step title="Error occurred" date="2015-04-17T10:08:54.318" type="error" text="Illegal characters in path." stackTrace="   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Kudu.Core.Deployment.DeploymentManager.GetDeploymentManifestPath(String id)
   at Kudu.Core.Deployment.DeploymentManager.GetActiveDeploymentManifestPath()
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" /><!-- duration: 16ms -->
    <step title="Cleaning up temp files" date="2015-04-17T10:08:54.349" /><!-- duration: 0ms -->
    <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2015-04-17T10:08:54.411" /><!-- duration: 78ms -->
  </step><!-- duration: 3392ms -->
  <step title="Outgoing response" date="2015-04-17T10:08:54.740" type="response" statusCode="204" statusText="No Content" Server="Microsoft-IIS/8.0" x-ms-request-id="ca3b00aa-d1ad-42f3-b540-a55dbbb56fcd" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 0ms -->
</step><!-- duration: 3564ms -->
```
The really weird thing is. I can not even redeploy old deployments that used to work. I get the same error....

**Comment by davidebbo** [comment]
Strange. The code that's throwing is here: https://github.com/projectkudu/kudu/blob/02abdbcc763d3d58ef5ef06a54c57e746046ad47/Kudu.Core/Deployment/DeploymentManager.cs#L834

        private string GetDeploymentManifestPath(string id)
        {
            return Path.Combine(GetRoot(id), Constants.ManifestFileName);
        }

        private string GetRoot(string id, bool ensureDirectory = true)
        {
            string path = Path.Combine(_environment.DeploymentsPath, id);

            if (ensureDirectory)
            {
                return FileSystemHelpers.EnsureDirectory(path);
            }

            return path;
        }

- `Constants.ManifestFileName` is constant, so probably not to blame.
- `id` in your case is `e781d28c2ddd94d2bc4965c4cba71d789dc3134d` which looks clean
- `_environment.DeploymentsPath` reallyshouldn't have unusual characters

If you connect with Kudu console and look around, you don't see anything that looks obviously corrupted in the paths? Try going into d:\home\site\deployments in particular.

**Comment by JakobOlsen** [comment]
Hi David.

There is nothing obvious to see in the console.

Is there something specific i can do? Or some log/dump i can paste/send ?

**Comment by davidebbo** [comment]
I made a private build that has this code:

        private string GetDeploymentManifestPath(string id)
        {
            try
            {
                return Path.Combine(GetRoot(id), Constants.ManifestFileName);
            }
            catch (Exception e)
            {
                throw new ArgumentException(String.Format("GetDeploymentManifestPath error, id={0}, GetRoot(id)={1}, ManifestFileName={2}", id, GetRoot(id), Constants.ManifestFileName), e);
            }
        }

To use it:
- download the zip from [here](https://dl.dropboxusercontent.com/u/2209341/Kudu.zip)
- go to Kudu console
- drag and drop the zip into the special zone in the Console fro dropping zip files
- restart your site
- test your scenario again and get the log like you did before, hopefully with more info

When you're done with private, you may need to set `WEBSITE_PRIVATE_EXTENSIONS=0` app setting in portal and restart your site before deleting the private Kudu.

**Comment by JakobOlsen** [comment]
Hi again David.

I appreciate your help! 
I uploaded the zip-file you sent, but it didn't make any difference.
I dropped it into the kudu console in both Chrome and IE, and i even upploaded it manually via FTP. Restarted everything...

The error is still the same - with no extra info.

Are you sure you linked the correct zip-file?

For completeness sake; here is the fresh log-file:
```
<step title="Incoming Request" date="2015-04-18T08:05:03.484" instance="90d06e" url="/api/deployments/573128dfaf67170db3010cec0f58b477fccd5034" method="PUT" type="request" pid="5296,2,18" Connection="Keep-Alive" Content-Length="0" Content-Type="text/plain; charset=utf-8" Accept="application/json" Accept-Language="en-US" Host="skirmish4242.scm.azurewebsites.net" User-Agent="Azure-Portal/5.3.00298.3" x-ms-client-request-id="472d3505-12a8-4f87-a869-7e5383a3c7c5-2015-04-18 08:06:47Z" x-ms-client-session-id="472d0f6f-4b32-4bf7-9ddc-1da6b69194e8" X-SITE-DEPLOYMENT-ID="Skirmish4242" X-MS-WAWS-JWT="" >
  <step title="DeploymentService.Deploy(id)" date="2015-04-18T08:05:03.515" >
    <step title="Executing external process" date="2015-04-18T08:05:03.531" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 78ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-18T08:05:03.624" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-18T08:05:03.798" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 47ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-18T08:05:03.860" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-18T08:05:03.860" type="process" path="git.exe" arguments="log -n 1 573128dfaf67170db3010cec0f58b477fccd5034 --" /><!-- duration: 109ms -->
    <step title="DeploymentManager.Deploy(id)" date="2015-04-18T08:05:03.970" >
      <step title="Collecting changeset information" date="2015-04-18T08:05:03.986" /><!-- duration: 47ms -->
      <step title="Updating to specific changeset" date="2015-04-18T08:05:04.066" >
        <step title="Executing external process" date="2015-04-18T08:05:04.288" type="process" path="git.exe" arguments="checkout 573128dfaf67170db3010cec0f58b477fccd5034 --force" /><!-- duration: 710ms -->
      </step><!-- duration: 948ms -->
      <step title="Updating submodules" date="2015-04-18T08:05:05.014" /><!-- duration: 72ms -->
      <step title="Determining deployment builder" date="2015-04-18T08:05:05.259" >
        <step title="Executing external process" date="2015-04-18T08:05:05.259" type="process" path="git.exe" arguments="ls-files *.csproj *.vbproj *.fsproj *.sln" /><!-- duration: 63ms -->
        <step title="Builder is WapBuilder" date="2015-04-18T08:05:05.338" /><!-- duration: 0ms -->
      </step><!-- duration: 94ms -->
    </step><!-- duration: 1415ms -->
    <step title="Error occurred" date="2015-04-18T08:05:05.384" type="error" text="Illegal characters in path." stackTrace="   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Kudu.Core.Deployment.DeploymentManager.GetRoot(String id, Boolean ensureDirectory)
   at Kudu.Core.Deployment.DeploymentManager.GetDeploymentManifestPath(String id)
   at Kudu.Core.Deployment.DeploymentManager.GetActiveDeploymentManifestPath()
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" /><!-- duration: 0ms -->
    <step title="Cleaning up temp files" date="2015-04-18T08:05:05.400" /><!-- duration: 0ms -->
    <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2015-04-18T08:05:05.568" /><!-- duration: 23ms -->
  </step><!-- duration: 2092ms -->
  <step title="Outgoing response" date="2015-04-18T08:05:05.607" type="response" statusCode="204" statusText="No Content" Server="Microsoft-IIS/8.0" x-ms-request-id="2d219ac9-f467-4d4a-925a-02931fc8a43e" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 16ms -->
</step><!-- duration: 2139ms -->
```

**Comment by davidebbo** [comment]
Did you make sure to drop it in the special area so it gets expanded? You should end up with a `D:\home\SiteExtensions\Kudu` folder.

If you go to the Kudu root, what Kudu version is it showing? Official should look like `44.40415.1492.0`, and private like `45.0.0.0`.

**Comment by JakobOlsen** [comment]
The Kudu build says: 45.0.0.0 (02abdbcc76)

If i press the link in the it takes me to this commit https://github.com/projectkudu/kudu/commit/02abdbcc763d3d58ef5ef06a54c57e746046ad47

Which doesn't have the codechange you mention....

**Comment by JakobOlsen** [comment]
I see it now.... It is a new error, and therefore we don't catch it with the change you made.

The exception is no longer thrown in GetDeploymentManifestPath, but in GetRoot.

**Comment by JakobOlsen** [comment]
I'm rambling.... We should still catch it with the change you made, but for some reason the exception is now thrown in GetRoot.

Confusion rising....

**Comment by JakobOlsen** [comment]
You are actually calling GetRoot in the catch clause - that's probably why we are seing the new error.

**Comment by JakobOlsen** [comment]
Right.... Took the time to clone Kudu and learn to build it. Fairly easy once i found the Setup-script :-)

Now i changed the code to this:
```
private string GetDeploymentManifestPath(string id)
        {
            try
            {
                return Path.Combine(GetRoot(id), Constants.ManifestFileName);
            }
            catch (Exception e)
            {
                throw new ArgumentException(String.Format("GetDeploymentManifestPath error, id={0}, DeploymentsPath={1}, ManifestFileName={2}", id, _environment.DeploymentsPath, Constants.ManifestFileName), e);
            }

        }
```

And the log-file now shows:
```
<step title="Incoming Request" date="2015-04-18T10:11:26.318" instance="90d06e" url="/api/deployments/12a575003eb1bedb496048c184aaddef2f6a1ff7" method="PUT" type="request" pid="3008,7,11" Connection="Keep-Alive" Content-Length="0" Content-Type="text/plain; charset=utf-8" Accept="application/json" Accept-Language="en-US" Host="skirmish4242.scm.azurewebsites.net" User-Agent="Azure-Portal/5.3.00298.3" x-ms-client-request-id="a0bde4bc-35c3-4b56-bc66-08861842737b-2015-04-18 10:13:11Z" x-ms-client-session-id="472d0f6f-4b32-4bf7-9ddc-1da6b69194e8" X-SITE-DEPLOYMENT-ID="Skirmish4242" X-MS-WAWS-JWT="" >
  <step title="DeploymentService.Deploy(id)" date="2015-04-18T10:11:26.411" >
    <step title="Executing external process" date="2015-04-18T10:11:26.476" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 76ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-18T10:11:26.552" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-18T10:11:26.802" type="process" path="git.exe" arguments="rev-parse --git-dir" /><!-- duration: 47ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-04-18T10:11:26.849" /><!-- duration: 0ms -->
    <step title="Executing external process" date="2015-04-18T10:11:26.864" type="process" path="git.exe" arguments="log -n 1 12a575003eb1bedb496048c184aaddef2f6a1ff7 --" /><!-- duration: 78ms -->
    <step title="DeploymentManager.Deploy(id)" date="2015-04-18T10:11:26.958" >
      <step title="Collecting changeset information" date="2015-04-18T10:11:26.974" /><!-- duration: 67ms -->
      <step title="Updating to specific changeset" date="2015-04-18T10:11:27.074" >
        <step title="Executing external process" date="2015-04-18T10:11:27.139" type="process" path="git.exe" arguments="checkout 12a575003eb1bedb496048c184aaddef2f6a1ff7 --force" /><!-- duration: 622ms -->
      </step><!-- duration: 687ms -->
      <step title="Updating submodules" date="2015-04-18T10:11:27.778" /><!-- duration: 53ms -->
      <step title="Determining deployment builder" date="2015-04-18T10:11:27.956" >
        <step title="Executing external process" date="2015-04-18T10:11:27.973" type="process" path="git.exe" arguments="ls-files *.csproj *.vbproj *.fsproj *.sln" /><!-- duration: 63ms -->
        <step title="Builder is WapBuilder" date="2015-04-18T10:11:28.082" /><!-- duration: 16ms -->
      </step><!-- duration: 158ms -->
    </step><!-- duration: 1202ms -->
    <step title="Error occurred" date="2015-04-18T10:11:28.176" type="error" text="GetDeploymentManifestPath error, id=                                        , DeploymentsPath=D:\home\site\deployments, ManifestFileName=manifest" stackTrace="   at Kudu.Core.Deployment.DeploymentManager.GetDeploymentManifestPath(String id)
   at Kudu.Core.Deployment.DeploymentManager.GetActiveDeploymentManifestPath()
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" innerText="Illegal characters in path." innerStackTrace="   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Kudu.Core.Deployment.DeploymentManager.GetDeploymentManifestPath(String id)" /><!-- duration: 0ms -->
    <step title="Cleaning up temp files" date="2015-04-18T10:11:28.195" /><!-- duration: 0ms -->
    <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2015-04-18T10:11:28.304" /><!-- duration: 109ms -->
  </step><!-- duration: 2017ms -->
  <step title="Outgoing response" date="2015-04-18T10:11:28.444" type="response" statusCode="204" statusText="No Content" Server="Microsoft-IIS/8.0" x-ms-request-id="08a25ece-0441-4064-911f-2799365e8d31" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 0ms -->
</step><!-- duration: 2142ms -->
```

So it seems that the id is the culprit.

**Comment by JakobOlsen** [comment]
So.......

I concluded that Kudu had somehow lost track of the ActiveDeployment, since that is where the id comes from.

So i hardcoded it.

```
private string GetActiveDeploymentManifestPath()
        {
            string id = "12a575003eb1bedb496048c184aaddef2f6a1ff7";//_status.ActiveDeploymentId;

            if (String.IsNullOrEmpty(id))
            {
                return null;
            }

            return GetDeploymentManifestPath(id);
        }
```

And now the deployment went fine.

Now i just need to revert the changes to kudu, and see if a brand new deployment goes well.

**Comment by JakobOlsen** [comment]
And i just confirmed with a fresh deployment that Kudu now works again.

So Kudu lost track of the active deployment. And come to think of it, when looking at the deployments tab in azure none of them were marked as active.

Thanks for the help David. It was truly awesome.

**Comment by davidebbo** [comment]
@JakobOlsen Great job in getting to the bottom of the issue!

I seem to recall seeing something like this in one or two occasions. What we observed is that certain files in super rare cases seem to get corrupted, and end up with the correct length but with all characters in it being ASCII zeros (i.e. the `NUL` character).

As an aside, do you have any feedback on getting started with building Kudu? Is there anything that could have made it easier?

**Comment by JakobOlsen** [comment]
Hi David,

Looking at the log file in notepad++ shows that the id was indeed a long string of NUL characters.

Building Kudu was pretty hassle-free once i found the KuduDevSetup.cmd - it wasn't mentioned at all in the guide i was initially following, so nothing worked..... But after stumbling upon it fairly randomly, i ran it and subsequently everything just worked.

The whole deployment by dropping a zip-file into a semi-hidden area of the kudu console was not the best user-experience. There was absolutely no feedback from the process, so i didn't really learn to trust it. That process could be a bit more verbose.
The way i deployed was just plopping the kudu.core.dll in manually via ftp. It was the only file touched by the small software changes i made, so it worked alright.
