### ISSUE TITLE
Access Denied Deleting File

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#1697]
I'm having an issue when using Github deployments after a nuget package was removed from my project.json. It seems when the file is attempted to be deleted, it fails:

```
KuduSync.NET from: 'D:\local\Temp\8d2bf9cda2495cf' to: 'D:\home\site'
Error: Access to the path 'Serilog.Sinks.Logentries.dll' is denied.
Copying file: 'ef'
Copying file: 'ef.cmd'
Copying file: 'gen'
Copying file: 'gen.cmd'
Copying file: 'web'
Copying file: 'web.cmd'
Copying file: 'approot\global.json'
Deleting file: 'approot\packages\Serilog.Sinks.Logentries\1.5.8\Serilog.Sinks.Logentries.nuspec'
Deleting file: 'approot\packages\Serilog.Sinks.Logentries\1.5.8\lib\net45\Serilog.Sinks.Logentries.dll'
An error has occurred during web site deployment.
```

**Comment by davidebbo** [comment]
It's strange for a couple reasons:
- normally, KuduSync has logic to rename/move files that can't be deleted, which usually works for DLLs
- normally, DLLs don't get loaded out of the NuGet packages folder

Can you try using Kudu Console to see what's going on? Check for file handles in Kudu Process Explorer, and use console to try to delete/rename the file.

**Comment by robfarmergt** [comment]
Here is the output from the file handles:

![image](https://cloud.githubusercontent.com/assets/4447784/9945643/6dae6b50-5d5c-11e5-872b-9016110d57c0.png)

Here is the log this time, looks like it had trouble with the directory now:

```
Cannot removed the 'to be deleted' directory, ignoring
Error: The process cannot access the file 'D:\home\site\approot\packages\Serilog.Sinks.Logentries\1.5.8\lib\net45' because it is being used by another process.
KuduSync.NET from: 'D:\local\Temp\8d2bfa06d57e935' to: 'D:\home\site'
Copying file: 'ef'
Copying file: 'ef.cmd'
Copying file: 'gen'
Copying file: 'gen.cmd'
Copying file: 'web'
Copying file: 'web.cmd'
Copying file: 'approot\global.json'
Deleting file: 'approot\packages\Serilog.Sinks.Logentries\1.5.8\Serilog.Sinks.Logentries.nuspec'
Deleting file: 'approot\packages\Serilog.Sinks.Logentries\1.5.8\lib\net45\Serilog.Sinks.Logentries.dll'
Deleting directory: 'approot\packages\Serilog.Sinks.Logentries\1.5.8\lib\net45'
An error has occurred during web site deployment.
```

I was able to DEL the directory manually, then I clicked the "Redeploy" button in azure and got this error:

```
Adding NuGet package D:\home\site\repository\wrap\DevExpress.PivotGrid.v15.1.Core\bin\Debug\DevExpress.PivotGrid.v15.1.Core.1.0.0.nupkg to D:\local\Temp\8d2bfa274c14c71\approot\packages
Installing DevExpress.PivotGrid.v15.1.Core.1.0.0
Add complete, 928ms elapsed
Removing D:\home\site\repository\wrap\DevExpress.PivotGrid.v15.1.Core\bin\Debug\DevExpress.PivotGrid.v15.1.Core.1.0.0.nupkg
System.IO.IOException: The process cannot access the file 'D:\home\site\repository\wrap\DevExpress.PivotGrid.v15.1.Core\bin\Debug\DevExpress.PivotGrid.v15.1.Core.1.0.0.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Framework.PackageManager.Publish.PublishProject.EmitNupkg(PublishRoot root)
   at Microsoft.Framework.PackageManager.Publish.PublishProject.Emit(PublishRoot root)
   at Microsoft.Framework.PackageManager.Publish.PublishRoot.Emit()
   at Microsoft.Framework.PackageManager.Publish.PublishManager.Publish()
   at Microsoft.Framework.PackageManager.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
An error has occurred during web site deployment.
```

**Comment by davidebbo** [comment]
I don't see the output of Find Handle in your screenshot. It should pop up a dialog that shows you the processes/handle that match pattern. Can you try searching for `PivotGrid` in there to see if anything has a lock?

**Comment by robfarmergt** [comment]
sorry, here you go
```
dnx.exe:2008 -> D:\home\site\repository\wrap\DevExpress.PivotGrid.v15.1.Core\bin\Debug\DevExpress.PivotGrid.v15.1.Core.1.0.0.nupkg
```

**Comment by davidebbo** [comment]
Oh, I just noticed you using dnx, which does work differently in term of loading stuff directly from the packages folder. That's sort of a DNX bug if it keeps some things locked such that further deployment is not possible (/cc @davidfowl).

Simplest way to get around it may be to stop the site and retry the deployment.

**Comment by robfarmergt** [comment]
ok, ill give it a shot

**Comment by davidebbo** [comment]
One thing that's puzzling is that I don't even see dnx.exe in your process list above. It may actually have been launched during **deployment** and that's what was holding on to it rather than the site runtime.

**Comment by robfarmergt** [comment]
Ok, so stopping the site and syncing the deployment again worked.

Happy to help you or @davidfowl troubleshoot some more. I can reproduce by adding the package back and removing it again. Just let me know.
