### ISSUE TITLE
Error deploying site on azure using github and kudu

### ISSUE THREAD

**Issue by hahmed** [projectkudu/kudu#1722]
I seem to be getting an error with my deployments. The restore seemed to have completed just fine 
- Restore complete, 4272ms elapsed.

The next part to run is related to the nuget config file which is failing.

I am using the exact same file as https://github.com/aspnet/live.asp.net/blob/dev/NuGet.Config

Do you need any more information?

````
NuGet Config files used:
    C:\DWASFiles\Sites\#1Team-Surventrix\AppData\NuGet\NuGet.Config
    D:\home\site\repository\NuGet.Config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532
System.ArgumentException: The path is not of a legal form.

   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
An error has occurred during web site deployment.
   at Microsoft.Dnx.Tooling.Publish.PublishManager.Normalize(String projectDir)
   at Microsoft.Dnx.Tooling.Publish.PublishManager..ctor(IServiceProvider hostServices, PublishOptions options)
   at Microsoft.Dnx.Tooling.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Dnx.Tooling.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
````

**Comment by hahmed** [comment]
The deployment file was generated by kuduscript which is (just in case you ask):

````
@if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

:: ----------------------
:: KUDU Deployment Script
:: Version: 1.0.2
:: ----------------------

:: Prerequisites
:: -------------

:: Verify node.js installed
where node 2>nul >nul
IF %ERRORLEVEL% NEQ 0 (
  echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
  goto error
)

:: Setup
:: -----

setlocal enabledelayedexpansion

SET ARTIFACTS=%~dp0%..\artifacts

IF NOT DEFINED DEPLOYMENT_SOURCE (
  SET DEPLOYMENT_SOURCE=%~dp0%.
)

IF NOT DEFINED DEPLOYMENT_TARGET (
  SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
)

IF NOT DEFINED NEXT_MANIFEST_PATH (
  SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

  IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
    SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
  )
)

IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g --silent
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)
IF NOT DEFINED DEPLOYMENT_TEMP (
  SET DEPLOYMENT_TEMP=%temp%\___deployTemp%random%
  SET CLEAN_LOCAL_DEPLOYMENT_TEMP=true
)

IF DEFINED CLEAN_LOCAL_DEPLOYMENT_TEMP (
  IF EXIST "%DEPLOYMENT_TEMP%" rd /s /q "%DEPLOYMENT_TEMP%"
  mkdir "%DEPLOYMENT_TEMP%"
)

IF DEFINED MSBUILD_PATH goto MsbuildPathDefined
SET MSBUILD_PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe
:MsbuildPathDefined
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Deployment
:: ----------

echo Handling ASP.NET 5 Web Application deployment.

:: Remove wwwroot if deploying to default location
IF "%DEPLOYMENT_TARGET%" == "%WEBROOT_PATH%" (
    FOR /F %%i IN ("%DEPLOYMENT_TARGET%") DO IF "%%~nxi"=="wwwroot" (
    SET DEPLOYMENT_TARGET=%%~dpi
    )
)

:: Remove trailing slash if present
IF "%DEPLOYMENT_TARGET:~-1%"=="\" (
    SET DEPLOYMENT_TARGET=%DEPLOYMENT_TARGET:~0,-1%
)


:: 1. Set DNX Path
set DNVM_CMD_PATH_FILE="%USERPROFILE%\.dnx\temp-set-envvars.cmd"
set DNX_RUNTIME="%USERPROFILE%\.dnx\runtimes\dnx-CLR-win-x86.1.0.0-beta7"

:: 2. Install DNX
call :ExecuteCmd PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='%DNVM_CMD_PATH_FILE%';& '%SCM_DNVM_PS_PATH%' " install 1.0.0-beta7 -arch x86 -r CLR %SCM_DNVM_INSTALL_OPTIONS%
IF !ERRORLEVEL! NEQ 0 goto error


:: 3. Run DNU Restore
call %DNX_RUNTIME%\bin\dnu restore "%DEPLOYMENT_SOURCE%" %SCM_DNU_RESTORE_OPTIONS%
IF !ERRORLEVEL! NEQ 0 goto error

:: 4. Run DNU Bundle
call %DNX_RUNTIME%\bin\dnu publish "project.json" --runtime %DNX_RUNTIME% --out "%DEPLOYMENT_TEMP%" %SCM_DNU_PUBLISH_OPTIONS%
IF !ERRORLEVEL! NEQ 0 goto error

:: 5. KuduSync
call %KUDU_SYNC_CMD% -v 50 -f "%DEPLOYMENT_TEMP%" -t "%DEPLOYMENT_TARGET%" -n "%NEXT_MANIFEST_PATH%" -p "%PREVIOUS_MANIFEST_PATH%" -i ".git;.hg;.deployment;deploy.cmd"
IF !ERRORLEVEL! NEQ 0 goto error
)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: Post deployment stub
IF DEFINED POST_DEPLOYMENT_ACTION call "%POST_DEPLOYMENT_ACTION%"
IF !ERRORLEVEL! NEQ 0 goto error

goto end

:: Execute command routine that will echo out when error
:ExecuteCmd
setlocal
set _CMD_=%*
call %_CMD_%
if "%ERRORLEVEL%" NEQ "0" echo Failed exitCode=%ERRORLEVEL%, command=%_CMD_%
exit /b %ERRORLEVEL%

:error
endlocal
echo An error has occurred during web site deployment.
call :exitSetErrorLevel
call :exitFromFunction 2>nul

:exitSetErrorLevel
exit /b 1

:exitFromFunction
()

:end
endlocal
echo Finished successfully.
````

**Comment by ahmelsayed** [comment]
Would it be possible to share a sample repository that repros this issue? It'll make the investigation much easier.

**Comment by hahmed** [comment]
@ahmelsayed I gave you access - it is a private repo. Let me know who else needs access if needs be.

**Comment by hahmed** [comment]
I just created a new repo - almost exactly the same as my private repo.

https://github.com/hahmed/TeamKudu

Let me know how I can help further...

**Comment by ahmelsayed** [comment]
the error I'm getting from `TeamKudu` repo is `Unable to locate Microsoft.Net.Http.Client >= 1.0.0-beta7`. That isn't the same as the one you're getting right?

**Comment by hahmed** [comment]
Nope, nothing like that at all... I will investigate, i basically cloned my entire repo and removed bootstrap toolkit references which was related to the views. So not sure why that happened.

**Comment by hahmed** [comment]
@ahmelsayed ok the latest version of the repo now shows exactly the error I get, can you check again please? You should see the error I mentioned.

**Comment by ahmelsayed** [comment]
yes, now I can see the same error. Thanks for providing the repro, I'll take a look now

**Comment by ahmelsayed** [comment]
okay I figured it out :)

Apparently `dnu publish` requires either the full path to `project.json` or `.\project.json` if it's relative to the current directory. it seems like a bug in dnx to me, but try to update your deploy.cmd here https://github.com/hahmed/TeamKudu/blob/master/deploy.cmd#L96 to either specify the full path, `%DEPLOYMENT_SOURCE%` is the root of your repo, or `.\project.json`.

Can you try that and let me know if that works for you?

**Comment by hahmed** [comment]
@ahmelsayed thanks, you are a :star: 

I had to hard code the full path in to get it to work. ```` .\project.json```` did not work.

I can now ping/pong into my site.

Seems as though I am getting some other kind of issue after deploying the site to azure, where would I raise this?

````
<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
````

**Comment by ahmelsayed** [comment]
Great! I'm glad you were able to get it to work.
I'd report this error to the [DNX](https://github.com/aspnet/dnx) guys. They're the best people to know about the runtime errors.

**Comment by snobu** [comment]
I've added `<add key="ASPNET_DETAILED_ERRORS" value="true" />` to web.config and got a bit more info:

```
:(  Oops.
500 Internal Server Error
One or more compilation errors occured:

D:\home\site\approot\src\repository\Startup.cs

The name 'ErrorPageOptions' does not exist in the current context
Show raw compilation error details

D:\home\site\approot\src\repository\Startup.cs(79,30): DNX,Version=v4.5.1 error CS0103: 
The name 'ErrorPageOptions' does not exist in the current context
```

**Comment by snobu** [comment]
Continued here: https://github.com/aspnet/dnx/issues/2896
