### ISSUE TITLE
System.FormatException: Off is not a valid value for TraceEventType. errors in application logs

### ISSUE THREAD

**Issue by ashelley** [projectkudu/kudu#1744]
Hello,

According to the documentation here:

https://github.com/projectkudu/kudu/wiki/Web-jobs#logging

"For continuous WebJobs - Console.Out and Console.Error are routed to the "application logs", they will show up as file, blob or table storage depends on your configuration of the application logs (similar to your Website)."

If I use the command 

```
$ azure site log tail sitename
```

I am able to see the logs as they are currently running.  However these logs are not written to D:\home\LogFiles\Application

The only logs I am able to retrieve for a continuous webjob is the first 100 lines per execution at

D:\home\data\jobs\continuous\jobname\job_log.txt

Because this file stops logging after 100 lines this is the only log I am able to retrieve for my continuous webjob:

```
[10/13/2015 19:49:08 > 13a748: WARN] Reached maximum allowed output lines for this run, to see all of the job's logs you can enable website application diagnostics
[10/13/2015 20:09:53 > 13a748: SYS INFO] WebJob is still running
[10/14/2015 07:33:10 > 13a748: SYS ERR ] Job failed due to exit code 1
```

right before 07:33:10 the application would have emitted a stack trace to the console so that I could see the reason for the crash.  However because this log is truncated I am unable to tell why it crashed from this log.

The main problem I am having is that the logs for this webjob should be available in D:\home\LogFiles\Application as per the documentation.  Note that I do have diagnostic logs turned on in my webapp and they are 

![image](https://cloud.githubusercontent.com/assets/3195045/10526829/f7299abc-7341-11e5-9598-a43cf3da8797.png)

# Steps to reproduce:

-1) Create a webapp and turn on diagnostic logs as per above image

-2) Add a continuous webjob to D:\home\site\wwwroot\App_Data\jobs\continuous\testjob here is a test script I used:

## app.js:
```javascript
var startDate = new Date();
var workerId = startDate.getTime();
var index = 0;
var pid = process.pid;

console.log('started workerid=', workerId, 'pid=', pid);

function run() {
	index++;
    console.log('log workerid =', workerId, 'pid=', pid, 'index=', index, 'start=', startDate.toISOString(), 'now=', (new Date()).toISOString());    
    setTimeout(function(){
        run();
    }, 60000);
}

run();
```

-3) use the azure cli to see that the output of the continuous job can be streamed:

```
$ azure site log tail sitename
...
2015-10-15T20:14:32  PID[2868] Information log workerid = 1444940072697 pid= 3752 index= 1 start= 2015-10-15T20:14:32.697Z now= 2015-10-15T20:14:32.712Z
2015-10-15T20:15:32  PID[2868] Information log workerid = 1444940072697 pid= 3752 index= 2 start= 2015-10-15T20:14:32.697Z now= 2015-10-15T20:15:32.724Z
2015-10-15T20:16:32  PID[2868] Information log workerid = 1444940072697 pid= 3752 index= 3 start= 2015-10-15T20:14:32.697Z now= 2015-10-15T20:16:32.724Z
```
Note that the above output tells me that the logs are being output properly, however they are not being persisted in the application logs D:\home\LogFiles\Application

-4) look in the application logs to try to find the logs by looking at the contents of D:\home\LogFiles\Application> 

## Expected results:

As per the documentation at https://github.com/projectkudu/kudu/wiki/Web-jobs#logging I would expect to see the non-truncated logs in the application logs.

## Actual results: 

Only truncated logs are available at D:\home\data\jobs\continuous\jobname\job_log.txt which prevents us from diagnosing long running continuous job crashes because the logs do not extend past 100 lines.

## Other notes: 

azure-cli seems to be able to tail off the log files from <somewhere> but I am unsure where these logs are available on the filesystem if at all.

I believe this is a bug however it could be that I just am unsure of the location of where these log files are stored.  

## Also note: 

to test to see if this is just a problem with logging node.js specific jobs I created a bash script which also does not seem to log to the application logs.  Here is the bash script I tested:

## run.sh
```bash
START=`date +"%Y-%m-%dT%H:%M:%SZ"`
WORKER=`date +%s`
COUNT=0
while true
do
  COUNT=$((COUNT+1))  
  echo worker id=$WORKER index=$COUNT start=$START now=`date +"%Y-%m-%dT%H:%M:%SZ"`
  sleep 1m
done
```

Any help is appreciated as I am having a difficult time solving crashes that occur late at night because I am unable to log exceptions.

Thank you,

-Adam

**Comment by ashelley** [comment]
Below is probably an unrelated issue but I was just doing more testing and I created a web app from scratch and now every time the webjob logs the output looks like this in 'azure site log tail sitename' however it might cause a problem with following reproduction steps so i wanted to make note of it:

```
2015-10-15T22:13:45
System.FormatException: Off is not a valid value for TraceEventType. ---> System.ArgumentException: Requested value 'Off' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AssignToPropertyOrField(Object propertyValue, Object o, String memberName, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertDictionaryToObject(IDictionary`2 dictionary, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.ReadConfigFile()

2015-10-15T22:13:46
System.FormatException: Off is not a valid value for TraceEventType. ---> System.ArgumentException: Requested value 'Off' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AssignToPropertyOrField(Object propertyValue, Object o, String memberName, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertDictionaryToObject(IDictionary`2 dictionary, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.ReadConfigFile()

2015-10-15T22:13:46
System.FormatException: Off is not a valid value for TraceEventType. ---> System.ArgumentException: Requested value 'Off' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.AssignToPropertyOrField(Object propertyValue, Object o, String memberName, JavaScriptSerializer serializer, Boolean throwOnError)
   at System.Web.Script.Serialization.ObjectConverter.ConvertDictionaryToObject(IDictionary`2 dictionary, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeInternal(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.ObjectConverter.ConvertObjectToTypeMain(Object o, Type type, JavaScriptSerializer serializer, Boolean throwOnError, Object& convertedObject)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.ReadConfigFile()
```

- The webjob is the same app.js as above
- Web job Continuous as per above
- deployment method, created an empty webapp added a job directory using the debug console ie) mkdir site\wwwroot\App_Data\jobs\continuous\jobname then uploaded app.js into the directory
- run azure site log tail sitename

Expected results: see logs (also see logs in LogFiles\Application as per the OP
Actual results: for log line the above stack traces are emitted (once per minute as per the script)

**Comment by davidebbo** [comment]
What's the content of your `D:\home\site\diagnostics\settings.json`? Use Kudu Console to find it.

**Comment by ashelley** [comment]
{
  "AzureDriveEnabled": true,
  "AzureDriveTraceLevel": "Information"
}

**Comment by ashelley** [comment]
OHH... in the one that's completely blowing up it is this:

{
  "AzureDriveEnabled": true,
  "AzureDriveTraceLevel": "Information",
  "AzureTableEnabled": false,
  "AzureTableTraceLevel": "Off",
  "AzureBlobEnabled": false,
  "AzureBlobTraceLevel": "Off"
}

**Comment by davidebbo** [comment]
That's weird, it should never be set to Off. Seems there is a bug somewhere. Do you remember the precise steps that led to it being in that state?

For now, edit the file and change "Off"  to false.

**Comment by ashelley** [comment]
okay... yeah i can try again.. definitely just typical interaction with the portal UI.  

-create a new webapp
-install my testing webjob manually as per above 
- enabe logging by clicking the button on the portal UI and setting the drop down to information and hitting save

**Comment by davidebbo** [comment]
Sorry, not quite: change "Off" to **"Error"**.

But we do really want to know how it got in that state (another case [here](https://social.msdn.microsoft.com/Forums/azure/en-US/017c95c9-eb6c-44e1-a605-6b9900059b48/log-is-not-working?forum=windowsazurewebsitespreview&prof=required))

**Comment by ashelley** [comment]
Okay I'll document my steps and see if i I can repro

**Comment by davidebbo** [comment]
Are you using https://manage.windowsazure.com/ or https://portal.azure.com/? And are you uploading the webjob via portal zip file or other deployment?

**Comment by ashelley** [comment]
I'm using portal and I am manually creating the file (in this instance) as per instructions above:

mkdir site\wwwroot\App_Data\jobs\continuous\jobname then uploaded app.js into the directory

I'm just trying to get to the bottom of not getting any persistent logs, this exception on setting the diagnostic settings was an unrelated side issue.

**Comment by ashelley** [comment]
I just tried again twice and it didn't repo but one thing to note is that might be a clue:

```
{
  "AzureDriveEnabled": true,
  "AzureDriveTraceLevel": "Information",
  "AzureTableEnabled": false,
  "AzureTableTraceLevel": "Off",
  "AzureBlobEnabled": false,
  "AzureBlobTraceLevel": "Off"
}
```

The problem case is prettyfied: has new line characters in it and has an indent

For example now I tried to reproduce it twice and I got this as the result:

{"AzureDriveEnabled":true,"AzureDriveTraceLevel":"Information","AzureTableEnabled":false,"AzureTableTraceLevel":"Error","AzureBlobEnabled":false,"AzureBlobTraceLevel":"Error"}

Notice how it's unformated: no newlines, no indents.

Initially I definitely didn't do anything "weird" to cause the problem case to happen. 

I was just setting up a brand new site for testing... followed the exact same steps as I had created the site only a minute before posting the update to my issue.  Sorry I can't really thing of anything specific I did differently.

**Comment by amitapl** [comment]
Note there are 3 sources for updating this file: portal (kudu api), the trace listener (.net) and interceptor (node.js).

**Comment by ashelley** [comment]
I believe the steps I took were beginning the initialization of the node.js webjob then trying to turn on the diagnostic logging,... one additional step I might have taken was connecting first to the log streaming service... 'azure site log tail sitename' before turning on diagnostic logging, after installing the webjob

**Comment by ashelley** [comment]
actually yes! that was the reproduction.. the above steps with one change:

1) create webapp
2) connect to log streaming service
3) add webjob
4) turn on logging

**Comment by davidebbo** [comment]
Ah yes, it does seem related to log streaming, thanks! We are investigating further.

**Comment by ashelley** [comment]
Another weird side effect of causing this bug (it has happened to me twice today now) is that after I caused this bug my .azure directory becomes 'corrupted' some how...

```
$ azure site log tail adam-log-test
info:    Executing command site log tail
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
error:   Error
info:    Error information has been recorded to C:\Users\Adam\.azure\azure.err
error:   site log tail command failed
```

Note that I've seen mention of these access denied errors on azure forums on msdn but I can't find this second... but also this starts happening:

https://github.com/Azure/azure-xplat-cli/issues/1646

twice today i've had to delete my .azure directory because of this... so I just wanted to make note that these bugs also might be related to what just happenned.

So I think something to do with log streaming possible causes these two additional issues too

**Comment by ashelley** [comment]
@davidebbo no problem... any ideas on my original issue?  I can't get logs passed 100 lines and it's killing me debugging these long running jobs as it dies over night and I am unable to diagnose without logs

**Comment by davidebbo** [comment]
@mathewc may know more about that one. But tell you what: we've so taken over this issue with a different topic that I think it would be best to rename this issue, and re-open your original one as a new issue. This will avoid confusion when reading through it.

**Comment by suwatch** [comment]
```
2015-10-15T22:13:45
System.FormatException: Off is not a valid value for TraceEventType. ---> System.ArgumentException: Requested value 'Off' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
```

As for the above issue, we found out the bug.  It is a combination of using `log tail` (aka. log streaming) feature and new preview portal.   We are working toward fixing that.

Good news is there is a simple work around.  
 - [vCurrent portal](https://manage.windowsazure.com) 
 - browse to your site's configuration tab
 - turn on (or off) application logging and save.

This should correct it.  Let us know otherwise.
