### ISSUE TITLE
The directory name is invalid with aspnet 5 deployment

### ISSUE THREAD

**Issue by s093294** [projectkudu/kudu#1803]
I am trying to deploy this project on azure website (a aspnet xproj project).
https://github.com/s-innovations/S-Innovations.Azure.Demos

the log files indicate something is going wrong. 

```
<step title="Incoming Request" date="2015-11-15T01:32:34.903" instance="b570fd" url="/deploy?scmType=GitHub" method="POST" type="request" pid="5824,2,31" Connection="Keep-Alive" Content-Length="102" Expect="100-continue" Host="pksorensentest.scm.azurewebsites.net" User-Agent="Azure-WebSites-Controller/49.0.8598.1583" x-ms-request-id="39974bad-2dfb-43f9-9ef6-d1a4ccb6f89d" X-SITE-DEPLOYMENT-ID="pksorensentest" >
  <step title="Cleanup Xml Logs" date="2015-11-15T01:32:34.903" /><!-- duration: 16ms -->
  <step title="FetchHandler" date="2015-11-15T01:32:34.950" >
    <step title="Attempting to fetch target branch master" date="2015-11-15T01:32:34.950" /><!-- duration: 16ms -->
    <step title="Assuming git repository at D:\home\site\repository" date="2015-11-15T01:32:34.997" /><!-- duration: 0ms -->
    <step title="Performing fetch based deployment" date="2015-11-15T01:32:35.059" >
      <step title="Creating temporary deployment" date="2015-11-15T01:32:35.059" /><!-- duration: 63ms -->
      <step title="DeploymentManager.Deploy(id)" date="2015-11-15T01:32:36.240" >
        <step title="Collecting changeset information" date="2015-11-15T01:32:36.256" /><!-- duration: 48ms -->
        <step title="Updating submodules" date="2015-11-15T01:32:36.335" /><!-- duration: 63ms -->
        <step title="Determining deployment builder" date="2015-11-15T01:32:36.493" >
          <step title="Specific project was specified: src/AzureKeyVaultDemo/AzureKeyVaultDemo.xproj" date="2015-11-15T01:32:36.509" /><!-- duration: 0ms -->
        </step><!-- duration: 16ms -->
        <step title="Purge deployment items" date="2015-11-15T01:32:36.618" >
          <step title="Remove e8ba7b057, Failed, received at 11/15/2015 1:13:29 AM" date="2015-11-15T01:32:36.665" /><!-- duration: 0ms -->
        </step><!-- duration: 47ms -->
      </step><!-- duration: 440ms -->
      <step title="Error occurred" date="2015-11-15T01:32:36.681" type="error" text="The directory name is invalid.
" stackTrace="   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Kudu.Core.Infrastructure.AspNet5Helper.TryAspNet5WebProject(String rootPath, String&amp; projectJsonPath)
   at Kudu.Core.Deployment.Generator.SiteBuilderFactory.ResolveProject(String repositoryRoot, String targetPath, IDeploymentSettingsManager perDeploymentSettings, IFileFinder fileFinder, Boolean tryWebSiteProject, SearchOption searchOption, Boolean specificConfiguration)
   at Kudu.Core.Deployment.Generator.SiteBuilderFactory.CreateBuilder(ITracer tracer, ILogger logger, IDeploymentSettingsManager settings, IFileFinder fileFinder)
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" /><!-- duration: 0ms -->
    </step><!-- duration: 1700ms -->
  </step><!-- duration: 1825ms -->
  <step title="Outgoing response" date="2015-11-15T01:32:36.790" type="response" statusCode="200" statusText="OK" Server="Microsoft-IIS/8.0" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 0ms -->
</step><!-- duration: 1887ms -->
```

Created the issue and will start debugging now to see what folder it is that do not exist/is invalid.

**Comment by s093294** [comment]
I looks like the builder expects a path to the folder containing the project.json and not a path to xproj file or project.json file.

Will test and report back
