### ISSUE TITLE
AutoSwap will still be triggered even when build failed during deployment

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1813]
from below log, build failed but kudu still trigger Auto-Swap

````xml

<step title="Incoming Request" date="2015-11-20T18:50:47.745" instance="43c13d" url="/deploy?scmType=BitbucketHg" method="POST" type="request" pid="10012,2,5" Connection="Keep-Alive" Content-Length="88" Expect="100-continue" User-Agent="Azure-WebSites-Controller/49.0.8598.1583" >
  <step title="FetchHandler" date="2015-11-20T18:50:47.777" >
    <step title="Attempting to fetch target branch default" date="2015-11-20T18:50:47.885" /><!-- duration: 16ms -->
    <step title="Found mercurial repository at D:\home\site\repository" date="2015-11-20T18:50:47.931" /><!-- duration: 0ms -->
    <step title="Performing fetch based deployment" date="2015-11-20T18:50:48.279" >
      <step title="Creating temporary deployment" date="2015-11-20T18:50:48.291" /><!-- duration: 141ms -->

      ...
      ...
      
      <step title="DeploymentManager.Deploy(id)" date="2015-11-20T18:50:54.526" >
        <step title="Collecting changeset information" date="2015-11-20T18:50:54.542" /><!-- duration: 47ms -->
        <step title="Updating submodules" date="2015-11-20T18:50:54.604" /><!-- duration: 47ms -->
        <step title="Determining deployment builder" date="2015-11-20T18:50:54.761" /><!-- duration: 89931ms -->
      </step><!-- duration: 90525ms -->
      <step title="Error occurred" date="2015-11-20T18:52:25.067" type="error" text="Unable to determine which solution file to build. ........" stackTrace="   at Kudu.Core.Deployment.Generator.SiteBuilderFactory.ThrowAmbiguousSolutionsError(IList`1 solutions)
   at Kudu.Core.Deployment.Generator.SiteBuilderFactory.CreateBuilder(ITracer tracer, ILogger logger, IDeploymentSettingsManager settings, IFileFinder fileFinder)
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__29.MoveNext()" /><!-- duration: 0ms -->
      <step title="WebHooksManager.PublishEventAsync: PostDeployment" date="2015-11-20T18:52:25.098" /><!-- duration: 78ms -->
    </step><!-- duration: 97069ms -->
    <step title="Requesting auto swap to slot name - &apos;production&apos;, operation id - &apos;AUTOSWAPe92c2a3c-43a5-47c7-ad63-8ca95fb3750f&apos;, deployment id - &apos;f9c6e713daa53ae722a233cecc4b747cd37411bb&apos;" date="2015-11-20T18:52:25.411" /><!-- duration: 0ms -->
  </step><!-- duration: 97649ms -->
  <step title="Outgoing response" date="2015-11-20T18:52:25.426" type="response" statusCode="200" statusText="OK" Server="Microsoft-IIS/8.0" X-MS-SWAP-OPERATIONID="AUTOSWAPe92c2a3c-43a5-47c7-ad63-8ca95fb3750f" X-MS-SWAP-SLOTNAME="production" X-MS-SWAP-DEPLOYMENTID="f9c6e713daa53ae722a233cecc4b747cd37411bb" Cache-Control="private" X-AspNet-Version="4.0.30319" /><!-- duration: 16ms -->
</step><!-- duration: 97697ms -->


````

**Comment by davidebbo** [comment]
Definitely not good if a failure still results in autoswap!

**Comment by ealsur** [comment]
@shrimpy @davidebbo if you need any extra info or tests, let me know :)
