### ISSUE TITLE
LibGit2Sharp should just emit the message when fallback to git

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#1838]
Below shows up in the trace (fetch private repo) and often times misleads that something was wrong.  It should be good enough to emit just the exception message - not the full exception stack.

```xml
            <step title="Warning" date="2015-12-17T19:17:20.347" type="warning" text="LibGit2SharpRepository fetch failed with LibGit2Sharp.LibGit2SharpException: Unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)" />
```

**Comment by davidebbo** [comment]
What's the repro? Does it happen every time continuous deployment kicks in for private GitHub/BB? Agree we should clean it up, since it's an expected libgit limitation.

**Comment by suwatch** [comment]
Just setup continuous with any private repo.   During fetch, we attempt to use LibGit2Sharp first and fail with `Unsupported URL protocol`.  We were merely too aggressive to trace the whole stack in trace xml and it stood out.
