### ISSUE TITLE
Remote external already exists. at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)

### ISSUE THREAD

**Issue by mskutin** [projectkudu/kudu#1841]
@suwatch 
Running into this during deployment:
```xml
<step title="Error occurred" date="2015-12-18T08:34:56.394" type="error" text="Remote &apos;external&apos; already exists." stackTrace="   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_create_with_fetchspec(RepositorySafeHandle repo, String name, String url, String refspec)
   at LibGit2Sharp.RemoteCollection.Add(String name, String url, String fetchRefSpec)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)
   at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger)
   at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass3.&lt;&lt;ProcessRequestAsync&gt;b__0&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Contracts.Infrastructure.LockExtensions.&lt;TryLockOperationAsync&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)" />
```
Workaround:
add to AppSettings:
`SCM_USE_LIBGIT2SHARP_REPOSITORY` = `0`

**Comment by suwatch** [comment]
We should at least be defensive as in [this](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L533-L546).   Good to know how to it got here as well.

**Comment by Dashue** [comment]
Just hit this issue now, was by a fluke that I stumbled upon this workaround

**Comment by watashiSHUN** [comment]
@Dashue @mskutin
can you reproduce this error consistently? if so I need more detail on your repo
it may be an issue with `gitlib2sharp`, but I can't seem to hit this failure with my repo

**Comment by Dashue** [comment]
Sorry can't remember what this relates to.

**Comment by mskutin** [comment]
I'm sorry, it was a long time ago, don't remember how to reproduce it.

**Comment by davidebbo** [comment]
Closing for now, but we can re-open later if you hit this again.
