### ISSUE TITLE
Gulp fails on deploying.

### ISSUE THREAD

**Issue by Dia6lo** [projectkudu/kudu#1930]
I'm trying to deploy my gulp application on Azure and I'm getting
`Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\src\assets\images\back.png'`
when my deployment script goes to this part:
```
:: 5. Run gulp transformations
IF EXIST "%DEPLOYMENT_TARGET%\gulpfile.js" (
  pushd "%DEPLOYMENT_TARGET%"
  echo Running gulp serve.
  call :ExecuteCmd gulp serve
  IF !ERRORLEVEL! NEQ 0 goto error
  popd
)
```

**Comment by suwatch** [comment]
was this the first time you tried and ran into issue or it used to work but suddenly stop working?   

If you run just the gulp part on [kudu console](https://github.com/projectkudu/kudu/wiki/Kudu-console) - are you able to repro the issue?  If so, share us the gulp file and we can try to investigate?

**Comment by Dia6lo** [comment]
I tried it first time and I can repro it in console.
Here is gulp file: https://gist.github.com/Dia6lo/d9dd7cbae23c45ad6e6c

**Comment by Dia6lo** [comment]
And this is module that causes error https://gist.github.com/Dia6lo/922a37a806836fa01d6d

**Comment by suwatch** [comment]
where is the `serve` gulp task?   I would need the package.json to install all dependencies for repro.   you could share the sitename here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?  I can take a look at your site and extract from there.

**Comment by Dia6lo** [comment]
http://aiuta.azurewebsites.net/

**Comment by suwatch** [comment]
We are able to repro in our local env now.   Let us know if it is a different issue.

```
[01:49:49] Using gulpfile D:\home\site\wwwroot\gulpfile.js
[01:49:49] Starting 'scripts'...
[01:49:53] Starting 'less'...
[01:49:57] all files 13.4 kB
[01:49:57] Finished 'scripts' after 7.76 s
[01:49:57] Finished 'less' after 3.77 s
[01:49:57] Starting 'inject'...
[01:49:58] gulp-inject 3 files into index.html.
[01:49:58] gulp-inject 9 files into index.html.
[01:49:58] Finished 'inject' after 1.2 s
[01:49:58] Starting 'watch'...
[01:49:58] 'watch' errored after 27 ms
[01:49:58] Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\src\assets\images\back.png'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Glob._readdir (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:577:20)
    at Glob._process (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:379:15)
    at Glob.<anonymous> (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:403:14)
    at Array.forEach (native)
    at Glob.<anonymous> (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:402:9)
    at Glob._readdir (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:554:32)
    at Glob._process (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:379:15)
    at Glob.<anonymous> (D:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js:403:14)
```

**Comment by Dia6lo** [comment]
Yes, this is an issue I've encountered.

**Comment by suwatch** [comment]
The issue is in glob.js (`d:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js`).

When running `gulp watch`, it iterates and calls `fs.readdirSync`on all files/folders.   It relies on `ENOTDIR` error code to detect if it is file (not a directory).   However, on Windows, if files is on network share, the error will be `ENOTSUP` instead.   glob.js needs to anticipate for that.    The issue also described [here](https://github.com/isaacs/node-glob/issues/205).

The simple fix is to add `case "ENOTSUP":` to `d:\home\site\wwwroot\node_modules\globule\node_modules\glob\glob.js` line 608.   See below.

```javascript
  // now handle errors, and cache the information
  if (er) switch (er.code) {
    case "ENOTDIR": // totally normal. means it *does* exist.
    case "ENOTSUP": // same as ENOTDIR if network drive
      this.statCache[f] = 1
      return cb.call(this, er)
    case "ENOENT": // not terribly unusual
```

**Comment by Dia6lo** [comment]
So I must do it every time my site deploys from git? (I assume that repository is cloned as a fresh copy every deploy)

**Comment by suwatch** [comment]
In short, just one time.   

The node modules for gulp is npm-installed on `d:\home\site\wwwroot`.  It is idempotent - so won't be overwrittten if already intalled.

**Comment by suwatch** [comment]
close for now.  please reopen if same issue continues.
