### ISSUE TITLE
Entity Framework Core 1.0 DB Migration - ReflectionTypeLoadException

### ISSUE THREAD

**Issue by justinyoo** [projectkudu/kudu#1977]
Hi, Team.

I managed to send a REST API call to KUDU to run EF Core database migration command like:

```
dnx ef database update -c MyDbContext -p MyEfModels
```

I was able to run the same command from my local box without any issue. However, if I run the same command at KUDU it complains:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
  at System.Reflection.RuntimeAssembly.get_DefinedTypes()
  at Microsoft.Data.Entity.Design.Internal.StartupInvoker..ctor(String startupAssemblyName, String environment)
  at Microsoft.Data.Entity.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment)
  at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass4_1.<.ctor>b__2()
  at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
  at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass5_0.<ListContexts>b__0()
  at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. 
```

It seems that some assemblies are missing to load but I'm not sure how I can debug it to get more details from the `LoaderExceptions` property of `ReflectionTypeLoadException`. It doesn't seem to be an issue at EF Core but at KUDU. Can anyone help me out, please?

Cheers,

**Comment by davidebbo** [comment]
Note sure. Maybe it's hitting some kind of [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) issue. Do you have a test Web App in that state that we can look at and try running the command in? Please specify the exact command to run (and from where) in Kudu Console.

**Comment by justinyoo** [comment]
@davidebbo Hmmm... I deployed a new test ASP.NET Core web app into new Azure Web App and run DB migration directly on KUDU. This time I couldn't reproduce the issue. I should deploy my **real** app to see the error. I'll get back to you next week.

**Comment by davidebbo** [comment]
Ok, closing for now, but happy to reopen if you get good repro to share.

**Comment by timdows** [comment]
@justinyoo, last week I had the same problem. As you specify the target project, this project, when the first migration is added, will not have the EntityFramework.MicrosoftSqlServer package installed.
You can verify this by opening your migration cs file and check if all the using namespaces are resolved.
