### ISSUE TITLE
GitHub webhook ping results in an error response

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2020]
I just setup GitHub as my deployment source and their initial [ping request](https://developer.github.com/webhooks/#ping-event) triggered my first deploy (successful), but returned an error to their webhook. This might be the same as #1250

The payload was:

``` json
{
  "zen": "Non-blocking is better than blocking.",
  "hook_id": 8495766,
  "hook": {
    "type": "Repository",
    "id": 8495766,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "form",
      "insecure_ssl": "1",
      "url": "https://$noop-web:...@noop-web.scm.azurewebsites.net/deploy?scmType=GitHub"
    },
    "updated_at": "2016-05-23T23:51:00Z",
    "created_at": "2016-05-23T23:51:00Z",
    "url": "https://api.github.com/repos/xt0rted/noop/hooks/8495766",
    "test_url": "https://api.github.com/repos/xt0rted/noop/hooks/8495766/test",
    "ping_url": "https://api.github.com/repos/xt0rted/noop/hooks/8495766/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 57268145,
    "name": "noop",
    "full_name": "xt0rted/noop",
    "owner": {
      "login": "xt0rted",
      "id": 831974,
      "avatar_url": "https://avatars.githubusercontent.com/u/831974?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/xt0rted",
      "html_url": "https://github.com/xt0rted",
      "followers_url": "https://api.github.com/users/xt0rted/followers",
      "following_url": "https://api.github.com/users/xt0rted/following{/other_user}",
      "gists_url": "https://api.github.com/users/xt0rted/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/xt0rted/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/xt0rted/subscriptions",
      "organizations_url": "https://api.github.com/users/xt0rted/orgs",
      "repos_url": "https://api.github.com/users/xt0rted/repos",
      "events_url": "https://api.github.com/users/xt0rted/events{/privacy}",
      "received_events_url": "https://api.github.com/users/xt0rted/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/xt0rted/noop",
    "description": "Test repository",
    "fork": false,
    "url": "https://api.github.com/repos/xt0rted/noop",
    "forks_url": "https://api.github.com/repos/xt0rted/noop/forks",
    "keys_url": "https://api.github.com/repos/xt0rted/noop/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/xt0rted/noop/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/xt0rted/noop/teams",
    "hooks_url": "https://api.github.com/repos/xt0rted/noop/hooks",
    "issue_events_url": "https://api.github.com/repos/xt0rted/noop/issues/events{/number}",
    "events_url": "https://api.github.com/repos/xt0rted/noop/events",
    "assignees_url": "https://api.github.com/repos/xt0rted/noop/assignees{/user}",
    "branches_url": "https://api.github.com/repos/xt0rted/noop/branches{/branch}",
    "tags_url": "https://api.github.com/repos/xt0rted/noop/tags",
    "blobs_url": "https://api.github.com/repos/xt0rted/noop/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/xt0rted/noop/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/xt0rted/noop/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/xt0rted/noop/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/xt0rted/noop/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/xt0rted/noop/languages",
    "stargazers_url": "https://api.github.com/repos/xt0rted/noop/stargazers",
    "contributors_url": "https://api.github.com/repos/xt0rted/noop/contributors",
    "subscribers_url": "https://api.github.com/repos/xt0rted/noop/subscribers",
    "subscription_url": "https://api.github.com/repos/xt0rted/noop/subscription",
    "commits_url": "https://api.github.com/repos/xt0rted/noop/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/xt0rted/noop/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/xt0rted/noop/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/xt0rted/noop/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/xt0rted/noop/contents/{+path}",
    "compare_url": "https://api.github.com/repos/xt0rted/noop/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/xt0rted/noop/merges",
    "archive_url": "https://api.github.com/repos/xt0rted/noop/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/xt0rted/noop/downloads",
    "issues_url": "https://api.github.com/repos/xt0rted/noop/issues{/number}",
    "pulls_url": "https://api.github.com/repos/xt0rted/noop/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/xt0rted/noop/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/xt0rted/noop/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/xt0rted/noop/labels{/name}",
    "releases_url": "https://api.github.com/repos/xt0rted/noop/releases{/id}",
    "deployments_url": "https://api.github.com/repos/xt0rted/noop/deployments",
    "created_at": "2016-04-28T03:32:05Z",
    "updated_at": "2016-05-23T13:46:49Z",
    "pushed_at": "2016-05-23T13:46:49Z",
    "git_url": "git://github.com/xt0rted/noop.git",
    "ssh_url": "git@github.com:xt0rted/noop.git",
    "clone_url": "https://github.com/xt0rted/noop.git",
    "svn_url": "https://github.com/xt0rted/noop",
    "homepage": null,
    "size": 12,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "C#",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 2,
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "xt0rted",
    "id": 831974,
    "avatar_url": "https://avatars.githubusercontent.com/u/831974?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/xt0rted",
    "html_url": "https://github.com/xt0rted",
    "followers_url": "https://api.github.com/users/xt0rted/followers",
    "following_url": "https://api.github.com/users/xt0rted/following{/other_user}",
    "gists_url": "https://api.github.com/users/xt0rted/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/xt0rted/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/xt0rted/subscriptions",
    "organizations_url": "https://api.github.com/users/xt0rted/orgs",
    "repos_url": "https://api.github.com/users/xt0rted/repos",
    "events_url": "https://api.github.com/users/xt0rted/events{/privacy}",
    "received_events_url": "https://api.github.com/users/xt0rted/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

The response to the webhook was:

**Headers**

```
Cache-Control: private
Content-Length: 6407
Content-Type: text/html; charset=utf-8
Date: Mon, 23 May 2016 23:51:01 GMT
Server: Microsoft-IIS/8.0
Set-Cookie: ARRAffinity=e46ca9d39e16b4f6ae09cde74b2421e29a0f9b47a1246ba8392124ae8c666359;Path=/;Domain=noop-web.scm.azurewebsites.net
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```

**Body**

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>Root element is missing.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Root element is missing.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.Xml.XmlException: Root element is missing.<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[XmlException: Root element is missing.]
   System.Xml.XmlTextReaderImpl.Throw(Exception e) +72
   System.Xml.XmlTextReaderImpl.ParseDocumentContent() +5481286
   System.Xml.XmlTextReaderImpl.Read() +163
   System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options) +44
   System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options) +64
   XmlSettings.XmlUtility.GetDocument(String path) +64
   XmlSettings.XmlUtility.GetDocument(XName rootName, String path, Boolean createIfNotExists) +52
   XmlSettings.Settings.GetDocument(Boolean createIfNotExists) +45
   XmlSettings.Settings.GetValue(String section, String key) +120

[InvalidOperationException: Unable to parse settings file]
   XmlSettings.Settings.GetValue(String section, String key) +340
   Kudu.Core.Settings.PerSiteSettingsProvider.GetValue(String key) +18
   Kudu.Core.Settings.DeploymentSettingsManager.GetValue(String key, Boolean preventUnification) +165
   Kudu.Contracts.Settings.DeploymentSettingsExtension.GetTraceLevel(IDeploymentSettingsManager settings) +23
   Kudu.Services.Web.App_Start.NinjectServices.GetLogger(IEnvironment environment, IKernel kernel) +42
   Kudu.Services.Web.App_Start.&lt;&gt;c__DisplayClass9_0.&lt;RegisterServices&gt;b__3() +13
   Kudu.Services.Web.Tracing.TraceServices.CreateRequestTracer(HttpContext httpContext) +278
   Kudu.Services.Web.Tracing.TraceModule.OnBeginRequest(Object sender, EventArgs e) +640
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +69
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

            </font>

    </body>
</html>
<!-- 
[XmlException]: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at XmlSettings.XmlUtility.GetDocument(String path)
   at XmlSettings.XmlUtility.GetDocument(XName rootName, String path, Boolean createIfNotExists)
   at XmlSettings.Settings.GetDocument(Boolean createIfNotExists)
   at XmlSettings.Settings.GetValue(String section, String key)
[InvalidOperationException]: Unable to parse settings file
   at XmlSettings.Settings.GetValue(String section, String key)
   at Kudu.Core.Settings.PerSiteSettingsProvider.GetValue(String key)
   at Kudu.Core.Settings.DeploymentSettingsManager.GetValue(String key, Boolean preventUnification)
   at Kudu.Contracts.Settings.DeploymentSettingsExtension.GetTraceLevel(IDeploymentSettingsManager settings)
   at Kudu.Services.Web.App_Start.NinjectServices.GetLogger(IEnvironment environment, IKernel kernel)
   at Kudu.Services.Web.App_Start.NinjectServices.<>c__DisplayClass9_0.<RegisterServices>b__3()
   at Kudu.Services.Web.Tracing.TraceServices.CreateRequestTracer(HttpContext httpContext)
   at Kudu.Services.Web.Tracing.TraceModule.OnBeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
--><!-- 
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->
```

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
