### ISSUE TITLE
Asp.net 1.0.0 (full framework) deployment

### ISSUE THREAD

**Issue by robfarmergt** [projectkudu/kudu#2098]
Is there an example project that I can reference to make sure my web app is going to be deployed properly to Azure?

I have migrated from beta8 to the 1.0.0 release and I'm having trouble getting the app running. It will deploy but I get various errors when trying to visit the site.

I get a standard 500 error page with no detail. If I change my `ASPNET_ENV` to `Development` and `ASPNET_DETAILEDERRORSS` to `1` I see the following:
```
System.InvalidOperationException: Unable to locate a project.json at 'D:\home\site\wwwroot\'.
   at Microsoft.Extensions.Configuration.UserSecrets.PathHelper.GetSecretsPath(IFileProvider provider)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
   at ProRata.Web.Startup..ctor(IHostingEnvironment env) in D:\home\site\repository\src\ProRata.Web\Startup.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider services, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
When I look at the directory structure from the Kudu control panel the path `D:\home\site\wwroot` contains another `wwwroot` directory. I'm spinning my wheels trying to get everything configured correctly.

**Comment by davidebbo** [comment]
Here is my test project: https://github.com/davidebbo-test/AspNetCoreVS

**Comment by robfarmergt** [comment]
Thank you @davidebbo I'm getting much closer. I'm not having trouble connecting to our database. I can connect to it locally but it seems the Azure web app can't.

I'm accessing the connection string using
`Configuration["Data:DefaultConnection:ConnectionString"]`

and in my Startup.cs I am doing:

```
var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
```

In Azure I have the connection string set in `Application settings > Connection Strings > Default Connection`

![image](https://cloud.githubusercontent.com/assets/4447784/17626532/9a54134e-607b-11e6-9cd2-51989f3a1123.png)

**Comment by robfarmergt** [comment]
Found the answer here: http://stackoverflow.com/a/37511645

Thanks for the help!

**Comment by davidebbo** [comment]
Adding @davidfowl and @glennc as I'm not too familiar with Core. What exactly does `Configuration["Data:DefaultConnection:ConnectionString"]` mean?

**Comment by davidebbo** [comment]
Our replied crossed. Glad you got it going!
