### ISSUE TITLE
ASP.NET Core 1.0.0 prepublish gulp commands not working

### ISSUE THREAD

**Issue by kspearrin** [projectkudu/kudu#2128]
My `project.json` contains the following:

    "scripts": {
        "prepublish": [ "npm install", "gulp build" ],
        "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    }

This always ran my gulp tasks fine in pre-RTM deployments with Kudu. Now that I have moved my project to 1.0.0 RTM, my gulp tasks are no longer being executed during Kudu deployments, and therefore, my CSS minification, etc does not happen. Building my project within VS runs the tasks as expected.

The deployment log shows the following:

```
...

remote:   D:\Program Files (x86)\dotnet\dotnet.exe build "D:\home\site\repository\src\Web" --configuration Release --no-dependencies
remote: ..............
remote:   Project Web (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation
remote:   Environment variables:
remote:   Path=D:\home\site\repository\src\Web\node_modules\.bin;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries/x86;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\bin;D:\Program Files (x86)\Git\usr\bin;D:\home\bin;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries\amd64;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\npm\3.3.6;C:\DWASFiles\Sites\#1imobile3portal__4596\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\SiteExtensions\Kudu\57.50815.2378\bin\NativeBinaries\amd64;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\57.50815.2378\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\npm\3.3.6;C:\DWASFiles\Sites\#1imobile3portal__4596\AppData\npm;D:\Program Files (x86)\bower\1.3.12;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\nodejs\4.1.2;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Microsoft Network Monitor 3;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs;D:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;E:\base\x64;E:\base\x86;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x64;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x86;D:\Program Files (x86)\dotnet;D:\Python27
remote:   D:\Program Files (x86)\dotnet\dotnet.exe publish "D:\home\site\repository\src\Web" --output "D:\local\Temp\PublishTemp\Portal44" --configuration Release --no-build
remote:   Publishing Web for .NETFramework,Version=v4.6.1/win7-x86
remote: ..........................
remote:   npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
remote:   npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
remote:   npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
remote:   npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
remote:   npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
remote: ..........
remote:   npm ERR! Windows_NT 6.2.9200
remote:   npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.1.2\\node.exe" "D:\\Program Files (x86)\\npm\\3.3.6\\node_modules\\npm\\bin\\npm-cli.js" "install"
remote:   npm ERR! node v4.1.2
remote:   npm ERR! npm  v3.3.6
remote:   npm ERR! Cannot read property 'localeCompare' of undefined
remote:   npm ERR!
remote: PUBLISH : npm ERR! If you need help, you may report this error at:  [D:\home\site\repository\src\Web\Portal.xproj]
remote:   npm ERR!     <https://github.com/npm/npm/issues>
remote:   npm ERR! Please include the following file with any support request:
remote:   npm ERR!     D:\home\site\repository\src\Web\npm-debug.log
remote:   [16:45:55] Local gulp not found in D:\home\site\repository\src\Web
remote:   [16:45:55] Try running: npm install gulp
remote: ...................................
remote:   Configuring the following project for use with IIS: 'D:\local\Temp\PublishTemp\Portal44'
remote:   Updating web.config at 'D:\local\Temp\PublishTemp\Portal44\web.config'
remote:   Configuring project completed successfully

...
```

> remote:   npm ERR! Cannot read property 'localeCompare' of undefined

It seems this is an issue with npm 3.3.6. https://github.com/npm/npm/issues/9766

**Comment by kspearrin** [comment]
It seems that after explicitly setting the following application settings environment variables for my azure web app, npm started to work again:

```
WEBSITE_NODE_DEFAULT_VERSION = 4.4.7
WEBSITE_NPM_DEFAULT_VERSION = 3.10.5
```

It seems that the default NPM version is for web apps is 3.3.6, which is broken.

However, my prepublish gulp command is still not being executed properly:

```
...

remote:   Total changes: 40 (40 added, 0 deleted, 0 updated, 0 parameters changed, 10041152 bytes copied)
remote:
remote:   D:\Program Files (x86)\dotnet\dotnet.exe build "D:\home\site\repository\src\Web" --configuration Release --no-dependencies
remote: .........
remote:   Project Web (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
remote:   Environment variables:
remote:   Path=D:\home\site\repository\src\Web\node_modules\.bin;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries/x86;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\bin;D:\Program Files (x86)\Git\usr\bin;D:\home\bin;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries\amd64;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\Git\usr\bin;C:\DWASFiles\Sites\#1imobile3portal__4596\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\nodejs\4.4.7;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Microsoft Network Monitor 3;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs;D:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;E:\base\x64;E:\base\x86;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x64;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x86;D:\Program Files (x86)\dotnet;D:\Python27
remote:   D:\Program Files (x86)\dotnet\dotnet.exe publish "D:\home\site\repository\src\Web" --output "D:\local\Temp\PublishTemp\Portal44" --configuration Release --no-build
remote:   Publishing Web for .NETFramework,Version=v4.6.1/win7-x86
remote:   npm WARN package.json Web@1.0.0 No README.md file found!
remote:   npm http GET https://registry.npmjs.org/jquery-validation-unobtrusive/3.2.5
remote:   npm http GET https://registry.npmjs.org/moment/2.10.6
remote:   npm http GET https://registry.npmjs.org/jquery-form/3.50.0
remote:   npm http GET https://registry.npmjs.org/bootstrap-daterangepicker/2.1.19
remote:   npm http GET https://registry.npmjs.org/knockout/3.4.0
remote:   npm http GET https://registry.npmjs.org/bootbox/4.4.0
remote:   npm http GET https://registry.npmjs.org/select2/4.0.3
remote:   npm http GET https://registry.npmjs.org/select2-bootstrap-theme/0.1.0-beta.4
remote:   npm http GET https://registry.npmjs.org/toastr/2.1.2
remote:   npm http GET https://registry.npmjs.org/ismobilejs/0.3.9
remote:   npm http GET https://registry.npmjs.org/block-ui/2.70.1
remote:   npm http GET https://registry.npmjs.org/sortablejs/1.4.2
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote:   npm http GET https://registry.npmjs.org/gulp-less/3.0.5
remote:   npm http GET https://registry.npmjs.org/gulp-uglify/1.5.1
remote:   npm http GET https://registry.npmjs.org/gulp-concat/2.6.0
remote:   npm http GET https://registry.npmjs.org/gulp-cssmin/0.1.7
remote:   npm http GET https://registry.npmjs.org/gulp-rename/1.2.2
remote:   npm http GET https://registry.npmjs.org/rimraf/2.5.0
remote:   npm http GET https://registry.npmjs.org/merge-stream/1.0.0
remote:   npm http GET https://registry.npmjs.org/run-sequence/1.1.5
remote:   npm http GET https://registry.npmjs.org/git-rev/0.2.1
remote:   npm http GET https://registry.npmjs.org/fs/0.0.2
remote:   npm http GET https://registry.npmjs.org/bootstrap/3.3.6
remote:   npm http GET https://registry.npmjs.org/jquery/2.1.4
remote:   npm http GET https://registry.npmjs.org/jquery-validation/1.14.0
remote:   npm http GET https://registry.npmjs.org/font-awesome/4.5.0
remote:   npm http GET https://registry.npmjs.org/metismenu/2.2.0
remote:   npm http GET https://registry.npmjs.org/highcharts-release/4.2.1
remote: .....
remote:   npm http GET https://registry.npmjs.org/jquery-validation-unobtrusive/3.2.5
remote:   npm http GET https://registry.npmjs.org/jquery-form/3.50.0
remote:   npm http GET https://registry.npmjs.org/select2/4.0.3
remote:   npm http GET https://registry.npmjs.org/bootstrap-daterangepicker/2.1.19
remote:   npm http GET https://registry.npmjs.org/knockout/3.4.0
remote:   npm http GET https://registry.npmjs.org/moment/2.10.6
remote:   npm http GET https://registry.npmjs.org/bootbox/4.4.0
remote:   npm http GET https://registry.npmjs.org/ismobilejs/0.3.9
remote:   npm http GET https://registry.npmjs.org/toastr/2.1.2
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote:   npm http GET https://registry.npmjs.org/select2-bootstrap-theme/0.1.0-beta.4
remote:   npm http GET https://registry.npmjs.org/gulp-less/3.0.5
remote:   npm http GET https://registry.npmjs.org/sortablejs/1.4.2
remote:   npm http GET https://registry.npmjs.org/block-ui/2.70.1
remote:   npm http GET https://registry.npmjs.org/rimraf/2.5.0
remote:   npm http GET https://registry.npmjs.org/gulp-uglify/1.5.1
remote:   npm http GET https://registry.npmjs.org/gulp-concat/2.6.0
remote:   npm http GET https://registry.npmjs.org/merge-stream/1.0.0
remote:   npm http GET https://registry.npmjs.org/run-sequence/1.1.5
remote:   npm http GET https://registry.npmjs.org/fs/0.0.2
remote:   npm http GET https://registry.npmjs.org/gulp-cssmin/0.1.7
remote:   npm http GET https://registry.npmjs.org/bootstrap/3.3.6
remote:   npm http GET https://registry.npmjs.org/font-awesome/4.5.0
remote:   npm http GET https://registry.npmjs.org/metismenu/2.2.0
remote:   npm http GET https://registry.npmjs.org/jquery-validation/1.14.0
remote:   npm http GET https://registry.npmjs.org/jquery/2.1.4
remote:   npm http GET https://registry.npmjs.org/highcharts-release/4.2.1
remote:   npm http GET https://registry.npmjs.org/gulp-rename/1.2.2
remote:   npm http GET https://registry.npmjs.org/git-rev/0.2.1
remote: ......................................................
remote:   npm http GET https://registry.npmjs.org/jquery-validation-unobtrusive/3.2.5
remote:   npm http GET https://registry.npmjs.org/jquery-form/3.50.0
remote:   npm http GET https://registry.npmjs.org/select2/4.0.3
remote: npm ERR! Error : SSL error : CERT_UNTRUSTED [D:\home\site\repository\src\Web\Portal.xproj]
remote:   npm ERR!     at ClientRequest.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
remote:   npm ERR!     at ClientRequest.g (events.js:156:14)
remote:   npm ERR!     at ClientRequest.emit (events.js:67:17)
remote:   npm ERR!     at HTTPParser.parserOnIncomingClient (http.js:1256:7)
remote:   npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
remote:   npm ERR!     at CleartextStream.socketOnData (http.js:1288:20)
remote:   npm ERR!     at CleartextStream._push (tls.js:375:27)
remote:   npm ERR!     at SecurePair.cycle (tls.js:734:20)
remote:   npm ERR!     at EncryptedStream.write (tls.js:130:13)
remote:   npm ERR!     at Socket.ondata (stream.js:38:26)
remote: npm ERR!  [Error : SSL error : CERT_UNTRUSTED] [D:\home\site\repository\src\Web\Portal.xproj]
remote:   npm ERR! You may report this log at:
remote:   npm ERR!     <http://github.com/isaacs/npm/issues>
remote:   npm ERR! or email it to:
remote:   npm ERR!     <npm-@googlegroups.com>
remote:   npm ERR! System Windows_NT 6.2.9200
remote:   npm ERR! command "D:\\Program Files (x86)\\nodejs\\\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
remote:   npm ERR! cwd D:\home\site\repository\src\Web
remote:   npm ERR! node -v v0.6.20
remote:   npm ERR! npm -v 1.1.37
remote: PUBLISH : npm ERR! message SSL error : CERT_UNTRUSTED [D:\home\site\repository\src\Web\Portal.xproj]
remote:   npm http GET https://registry.npmjs.org/bootstrap-daterangepicker/2.1.19
remote:   npm http GET https://registry.npmjs.org/moment/2.10.6
remote:   npm http GET https://registry.npmjs.org/knockout/3.4.0
remote:   npm http GET https://registry.npmjs.org/bootbox/4.4.0
remote:   npm http GET https://registry.npmjs.org/ismobilejs/0.3.9
remote:   npm http GET https://registry.npmjs.org/toastr/2.1.2
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote:   npm http GET https://registry.npmjs.org/select2-bootstrap-theme/0.1.0-beta.4
remote:   npm http GET https://registry.npmjs.org/gulp-less/3.0.5
remote:   npm http GET https://registry.npmjs.org/block-ui/2.70.1
remote:   npm http GET https://registry.npmjs.org/sortablejs/1.4.2
remote:   npm http GET https://registry.npmjs.org/rimraf/2.5.0
remote:   npm http GET https://registry.npmjs.org/gulp-concat/2.6.0
remote:   npm http GET https://registry.npmjs.org/merge-stream/1.0.0
remote:   npm http GET https://registry.npmjs.org/gulp-uglify/1.5.1
remote:   npm http GET https://registry.npmjs.org/run-sequence/1.1.5
remote:   npm http GET https://registry.npmjs.org/gulp-cssmin/0.1.7
remote:   npm http GET https://registry.npmjs.org/fs/0.0.2
remote:   npm http GET https://registry.npmjs.org/bootstrap/3.3.6
remote:   npm http GET https://registry.npmjs.org/font-awesome/4.5.0
remote:   npm http GET https://registry.npmjs.org/metismenu/2.2.0
remote:   npm http GET https://registry.npmjs.org/jquery-validation/1.14.0
remote:   npm http GET https://registry.npmjs.org/jquery/2.1.4
remote:   npm http GET https://registry.npmjs.org/highcharts-release/4.2.1
remote:   npm http GET https://registry.npmjs.org/gulp-rename/1.2.2
remote:   npm http GET https://registry.npmjs.org/git-rev/0.2.1
remote:   npm
remote:   [14:26:36] Local gulp not found in D:\home\site\repository\src\Web
remote:   [14:26:36] Try running: npm install gulp
remote: ........................
remote:   Configuring the following project for use with IIS: 'D:\local\Temp\PublishTemp\Portal44'
remote:   Updating web.config at 'D:\local\Temp\PublishTemp\Portal44\web.config'
remote:   Configuring project completed successfully
remote:   publish: Published to D:\local\Temp\PublishTemp\Portal44
remote:   Published 1/1 projects successfully
remote:   Publishing with publish method [FileSystem]
remote:   Publishing files to D:\local\Temp\8d3d7f3e6851eab
remote:   Executing command ["D:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:manifest='D:\local\Temp\PublishTemp\obj\Portal44\SourceManifest.xml' -dest:manifest='D:\local\Temp\PublishTemp\obj\Portal44\DestinationManifest.xml' -verb:sync -enableRule:DoNotDeleteRule -retryAttempts:20 -disablerule:BackupRule]
remote:   Info: Adding directory (D:\local\Temp\8d3d7f3e6851eab\Areas).

...
```

I see it run this:

```
remote:   [14:26:36] Try running: npm install gulp
remote: ........................
```

But as you can see, no tasks run.

**Comment by davidebbo** [comment]
The default Node for new apps was recently changed to 4.4.7, and that maps to npm 2.15.8 (see https://raw.githubusercontent.com/nodejs/node/v4.4.7/deps/npm/package.json).

But if you want anything different from the official npm version that matches the Node build, then `WEBSITE_NPM_DEFAULT_VERSION` is the way to go.

**Comment by davidebbo** [comment]
Sorry, I missed that you still had an issue even with that build. Could you [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) that demonstrates the issue?

**Comment by kspearrin** [comment]
Please don't close the issue as it is still not resolved.

Here is a repo that shows the problem. It's just a standard ASP.NET Core 1.0.0 project with a gulpfile and `"prepublish": [ "npm install", "gulp build" ],` set in project.json, as described above.

https://github.com/kspearrin/kudu-gulp-issue

Simply add a remote for an azure website kudu deployment and push to it.

```

...


remote:   Environment variables:
remote:   Path=D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries/x86;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\libexec\git-core;D:\Program Files (x86)\Git\mingw32\bin;D:\Program Files (x86)\Git\usr\bin;D:\home\bin;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\NativeBinaries\amd64;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\57.50831.2397\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\Git\usr\bin;C:\DWASFiles\Sites\#1imobile3portal__4596\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\nodejs\4.4.7;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0;D:\Program Files\Microsoft Network Monitor 3;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs;D:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;E:\base\x64;E:\base\x86;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x64;D:\Packages\GuestAgent\GuestAgent\LegacyRuntime\x86;D:\Program Files (x86)\dotnet;D:\Python27
remote:   D:\Program Files (x86)\dotnet\dotnet.exe publish "D:\home\site\repository\src\WebApplication6" --output "D:\local\Temp\PublishTemp\WebApplication665" --configuration Release --no-build
remote:   Publishing WebApplication6 for .NETFramework,Version=v4.6/win7-x86
remote:   npm WARN package.json WebApplication6@1.0.0 No README.md file found!
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote: .......
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote: .......................................................
remote:   npm http GET https://registry.npmjs.org/gulp/3.9.0
remote: npm ERR! Error : SSL error : CERT_UNTRUSTED [D:\home\site\repository\src\WebApplication6\WebApplication6.xproj]
remote:   npm ERR!     at ClientRequest.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:440:26)
remote:   npm ERR!     at ClientRequest.g (events.js:156:14)
remote:   npm ERR!     at ClientRequest.emit (events.js:67:17)
remote:   npm ERR!     at HTTPParser.parserOnIncomingClient (http.js:1256:7)
remote:   npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
remote:   npm ERR!     at CleartextStream.socketOnData (http.js:1288:20)
remote:   npm ERR!     at CleartextStream._push (tls.js:375:27)
remote:   npm ERR!     at SecurePair.cycle (tls.js:734:20)
remote:   npm ERR!     at EncryptedStream.write (tls.js:130:13)
remote:   npm ERR!     at Socket.ondata (stream.js:38:26)
remote: npm ERR!  [Error : SSL error : CERT_UNTRUSTED] [D:\home\site\repository\src\WebApplication6\WebApplication6.xproj]
remote:   npm ERR! You may report this log at:
remote:   npm ERR!     <http://github.com/isaacs/npm/issues>
remote:   npm ERR! or email it to:
remote:   npm ERR!     <npm-@googlegroups.com>
remote:   npm ERR! System Windows_NT 6.2.9200
remote:   npm ERR! command "D:\\Program Files (x86)\\nodejs\\\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
remote:   npm ERR! cwd D:\home\site\repository\src\WebApplication6
remote:   npm ERR! node -v v0.6.20
remote:   npm ERR! npm -v 1.1.37
remote: PUBLISH : npm ERR! message SSL error : CERT_UNTRUSTED [D:\home\site\repository\src\WebApplication6\WebApplication6.xproj]
remote:   [15:03:16] Local gulp not found in D:\home\site\repository\src\WebApplication6
remote:   [15:03:16] Try running: npm install gulp
remote:   Configuring the following project for use with IIS: 'D:\local\Temp\PublishTemp\WebApplication665'
remote:   Updating web.config at 'D:\local\Temp\PublishTemp\WebApplication665\web.config'
remote:   Configuring project completed successfully
remote:   publish: Published to D:\local\Temp\PublishTemp\WebApplication665
remote:   Published 1/1 projects successfully
remote:   Publishing with publish method [FileSystem]
remote:   Publishing files to D:\local\Temp\8d3d8c21b366c7b
remote:   Executing command ["D:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:manifest='D:\local\Temp\PublishTemp\obj\WebApplication665\SourceManifest.xml' -dest:manifest='D:\local\Temp\PublishTemp\obj\WebApplication665\DestinationManifest.xml' -verb:sync -enableRule:DoNotDeleteRule -retryAttempts:20 -disablerule:BackupRule]
remote:   Info: Adding file (D:\local\Temp\8d3d8c21b366c7b\appsettings.json).
remote:   Info: Adding file (D:\local\Temp\8d3d8c21b366c7b\libuv.dll).
remote:   Info: Adding file (D:\local\Temp\8d3d8c21b366c7b\Microsoft.AspNetCore.Antiforgery.dll).
remote:   Info: Adding file (D:\local\Temp\8d3d8c21b366c7b\Microsoft.AspNetCore.Authorization.dll).


...
```

As you can see, it runs this

```
remote:   [15:03:16] Try running: npm install gulp
```

but never executes the `build` task.

This works fine when running `dotnet publish` locally and worked with Kudu in pre-RTM versions just fine.

Locally:

```
$ dotnet publish
Publishing WebApplication6 for .NETFramework,Version=v4.6/win7-x64
[11:06:00] Warning: gulp version mismatch:
[11:06:00] Global gulp is 3.9.1
[11:06:00] Local gulp is 3.9.0
[11:06:00] Using gulpfile C:\Projects\WebApplication6\src\WebApplication6\gulpfile.js
[11:06:00] Starting 'build'...
BUILDING!!!!!!!!!!!!!!!!!!!!
Project WebApplication6 (.NETFramework,Version=v4.6) was previously compiled. Skipping compilation.
Configuring the following project for use with IIS: 'C:\Projects\WebApplication6\src\WebApplication6\bin\Debug\net46\win7-x64\publish'
Updating web.config at 'C:\Projects\WebApplication6\src\WebApplication6\bin\Debug\net46\win7-x64\publish\web.config'
Configuring project completed successfully
publish: Published to C:\Projects\WebApplication6\src\WebApplication6\bin\Debug\net46\win7-x64\publish
Published 1/1 projects successfully
```

**Comment by davidebbo** [comment]
Thanks for the repo. I was able to repro that error. I can also repro it in Kudu Console by directly running `npm install gulp@3.9.0`. Frankly, I don't understand why that would fail with a cert issue, given that it's hitting the official npm server.

This [StackOverflow question](http://stackoverflow.com/questions/36998168/azure-web-app-kudu-configuration) seems to deal with the same situtation. One suggestion there is to run `npm config set strict-ssl false` to disable verification, through security wise that's not ideal.

**Comment by davidebbo** [comment]
Oh, I see the problem: you set the npm version to `3.10.5`, but that specific build is actually not available on Azure, so it ends up defaulting to an ancient 1.x build. Try using `3.10.3` instead.

**Comment by kspearrin** [comment]
Looks like that fixed it @davidebbo . Is there anywhere that information is published for future reference (or just information on `WEBSITE_*` app settings in general)? I couldn't find any. Thanks!

**Comment by davidebbo** [comment]
See https://github.com/projectkudu/kudu/wiki/Configurable-settings for all the `WEBSITES_` settings (or at least many of them). For the list of supported Node, click on the *Runtime versions* link from the root of the Kudu site.
