### ISSUE TITLE
Consider retry when BuildJobs failed due to IO (file storage) issue.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2190]
We should consider improve robust (for instance, retry) for certain IO file storage exceptions.  Such as, below.

```
System.IO.IOException: The device is not ready.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at System.IO.Abstractions.DirectoryWrapper.GetFiles(String path, String searchPattern)
   at Kudu.Core.Infrastructure.FileSystemHelpers.GetFiles(String path, String pattern)
   at Kudu.Core.Jobs.ContinuousJobsManager.UpdateDetailedStatus(ContinuousJob job, String jobsSpecificDataPath)
   at Kudu.Core.Jobs.ContinuousJobsManager.UpdateJob(ContinuousJob job)
   at Kudu.Core.Jobs.JobsManagerBase`1.BuildJob(DirectoryInfoBase jobDirectory, Boolean nullJobOnError)
   at Kudu.Core.Jobs.ContinuousJobsManager.GetJob(String jobName)
   at Kudu.Core.Jobs.ContinuousJobsManager.OnJobChanged(String jobName)
   at Kudu.Core.Jobs.JobsManagerBase`1.OnJobChanged(String jobName)
   at Kudu.Core.Jobs.JobsFileWatcher.OnMakeChanges(Object state)
```

```
System.IO.InternalBufferOverflowException: Too many changes at once in directory:D:\home\site\wwwroot\App_Data\jobs\continuous
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
