### ISSUE TITLE
Deploying fails - node.js app - native module hummus

### ISSUE THREAD

**Issue by storafrid** [projectkudu/kudu#2225]
Hi, this should be somewhat fixed according to https://github.com/projectkudu/kudu/issues/1076#issuecomment-156845856 but still fails for the module `hummus`. I'm guessing you wanted to know which modules still fails. Also see #2200 which is highly related.

```
{
  "name": "azure-kudu-hummus-test",
  "version": "1.0.0",
  "description": "",
  "engines": {
    "node": "4.6.0", // have tried a myriad of different versions
    "npm": "3.9.5" // here as well
  },
  "dependencies": {
    "hummus": "^1.0.62"
  }
}
```

**Comment by davidebbo** [comment]
@storafrid what specific error are you getting? Note that the support for native modules is still limited.

**Comment by nestenborg** [comment]
Attached is the log file from the build, do you need the npm-debug file as well?

Thanks
[lwip_logs.txt](https://github.com/projectkudu/kudu/files/596882/lwip_logs.txt)

**Comment by storafrid** [comment]
Hi, we're aware that not all native modules works at this time. Thought you might be interested in one that doesn't work, to aid you in finding out why. The prerequisites for this module (`hummus`) should just be VC++ Build Tools and Python 2.7, i.e. the minimum native build support. So I believe it's a good test case.

I've extracted the parts of the log that are probably most interesting:

```
... [lots of stuff]

19582 silly install hummus@1.0.64 D:\home\site\wwwroot\node_modules\.staging\hummus-541ec1a5
19583 info lifecycle hummus@1.0.64~install: hummus@1.0.64
19584 verbose lifecycle hummus@1.0.64~install: unsafe-perm in lifecycle true
19585 verbose lifecycle hummus@1.0.64~install: PATH: D:\Program Files (x86)\npm\3.9.5\node_modules\npm\bin\node-gyp-bin;D:\home\site\wwwroot\node_modules\hummus\node_modules\.bin;D:\home\site\wwwroot\node_modules\.bin;D:\Program Files (x86)\nodejs\4.6.0;D:\Program Files (x86)\SiteExtensions\Kudu\59.51109.2534\bin\NativeBinaries/amd64;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\59.51109.2534\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files (x86)\Git\bin;D:\Program Files (x86)\Git\usr\bin;D:\Program Files (x86)\npm\3.3.12;C:\DWASFiles\Sites\#1markis-wf__b421\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\nodejs\5.4.0;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Git\cmd;D:\Program Files\Microsoft Network Monitor 3\;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs\;D:\Program Files (x86)\Mercurial\;d:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;D:\Program Files (x86)\dotnet;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
19586 verbose lifecycle hummus@1.0.64~install: CWD: D:\home\site\wwwroot\node_modules\hummus
19587 silly lifecycle hummus@1.0.64~install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
19588 silly lifecycle hummus@1.0.64~install: Returned: code: 1  signal: null
19589 info lifecycle hummus@1.0.64~install: Failed to exec install script

... [lots of stuff]

19652 verbose stack Error: hummus@1.0.64 install: `node-pre-gyp install --fallback-to-build`
19652 verbose stack Exit status 1
19652 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\3.9.5\node_modules\npm\lib\utils\lifecycle.js:245:16)
19652 verbose stack     at emitTwo (events.js:87:13)
19652 verbose stack     at EventEmitter.emit (events.js:172:7)
19652 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\3.9.5\node_modules\npm\lib\utils\spawn.js:24:14)
19652 verbose stack     at emitTwo (events.js:87:13)
19652 verbose stack     at ChildProcess.emit (events.js:172:7)
19652 verbose stack     at maybeClose (internal/child_process.js:829:16)
19652 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19653 verbose pkgid hummus@1.0.64
19654 verbose cwd D:\home\site\wwwroot
19655 error Windows_NT 6.2.9200
19656 error argv "D:\\Program Files (x86)\\nodejs\\4.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.9.5\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
19657 error node v4.6.0
19658 error npm  v3.9.5
19659 error code ELIFECYCLE
19660 error hummus@1.0.64 install: `node-pre-gyp install --fallback-to-build`
19660 error Exit status 1
19661 error Failed at the hummus@1.0.64 install script 'node-pre-gyp install --fallback-to-build'.
19661 error Make sure you have the latest version of node.js and npm installed.
19661 error If you do, this is most likely a problem with the hummus package,
19661 error not with npm itself.
19661 error Tell the author that this fails on your system:
19661 error     node-pre-gyp install --fallback-to-build
19661 error You can get information on how to open an issue for this project with:
19661 error     npm bugs hummus
19661 error Or if that isn't available, you can get their info via:
19661 error     npm owner ls hummus
19661 error There is likely additional logging output above.
19662 verbose exit [ 1, true ]
```

**Comment by davidebbo** [comment]
@storafrid @nestenborg we made some changes which should help, as long as you're running on a dedicated plan (i.e. not Free/Shared). Can you give it a try?
