### ISSUE TITLE
Git Push: auto awap failing with Could not load assembly Newtonsoft.Json, Version=6.0.0.0

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2260]
The issue was we upgraded Kudu to use [NewtonSoft 9.0.0](https://github.com/projectkudu/kudu/commit/121eef5fe9f1d987bc0662eee72ca166cfdcb5c0 ).  However, System.Net.Http.Formatting still depends the old one (6.0.0),   Since we don't have binding redirection for kudu.exe (post receive hook scenario), the call after deployment successful failed with missing assembly.

```csharp
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kudu.Console.Program.PerformDeploy(String appRoot, String wapTargets, String deployer, String lockPath, IEnvironment env, IDeploymentSettingsManager settingsManager, TraceLevel level, ITracer tracer, ITraceFactory traceFactory, IOperationLock deploymentLock)" innerText="Could not load file or assembly &apos;Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed&apos; or one of its dependencies. The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)" innerStackTrace="   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor()
   at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor()
   at System.Net.Http.HttpClientExtensions.PostAsJsonAsync[T](HttpClient client, String requestUri, T value, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientExtensions.PostAsJsonAsync[T](HttpClient client, String requestUri, T value)
   at Kudu.Core.Infrastructure.OperationClient.&lt;PostAsync&gt;d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Deployment.AutoSwapHandler.&lt;HandleAutoSwap&gt;d__6.MoveNext()
```

**Comment by davidebbo** [comment]
We need to have a good way of not forgetting to update this file the next time we update newton, or the same thing will happen again.

**Comment by suwatch** [comment]
Add the test should suffice.
