### ISSUE TITLE
cli deploy from source control error

### ISSUE THREAD

**Issue by cephalin** [projectkudu/kudu#2372]
### Repro steps in CLI
Create Linux app service plan
```
az appservice plan create --name myAppServicePlan --resource-group myResourceGroup2 --sku S1 --is-linux --location "West US"
```
Create web app
```
az appservice web create --name cephalin-nodejs1 --resource-group myResourceGroup2 --plan myAppServicePlan
```
Configure node version 6.9.3
```
az appservice web config update --node-version 6.9.3 --name cephalin-nodejs1 --resource-group myResourceGroup2
```
Configure GitHub deployment (just an Express.js app)
```
az appservice web source-control config --name cephalin-nodejs1 --resource-group myResourceGroup2 --repo-url "
https://github.com/Azure-Samples/app-service-web-nodejs-get-started.git" --branch master --manual-integration
```

And here's the output
```
Operation failed with status: 200. Details: Resource state Failed
```

### The log/error given by the failure.
Here's the trace error from the kudu deployment:
```xml
<step title="Error occurred" date="2017-03-21T14:46:32.460" type="error" text="/opt/npm/3.10.8/node_modules/npm/bin/npm:2
(set -o igncr) 2&gt;/dev/null &amp;&amp; set -o igncr; # cygwin encoding fix
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/bin/bash &quot;/home/site/deployments/tools/deploy.sh&quot;" stackTrace="  at Kudu.Core.Infrastructure.Executable.ExecuteInternal (Kudu.Contracts.Tracing.ITracer tracer, System.Func`2[T,TResult] onWriteOutput, System.Func`2[T,TResult] onWriteError, System.Text.Encoding encoding, System.String arguments, System.Object[] args) [0x0018e] in &lt;2d2f67d4d9ca4ebdb0d017f393081a49&gt;:0 
  at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter (Kudu.Core.Deployment.ILogger logger, Kudu.Contracts.Tracing.ITracer tracer, System.String arguments, System.Object[] args) [0x00044] in &lt;2d2f67d4d9ca4ebdb0d017f393081a49&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in &lt;f712f98eb8e445c8918edaf595bbe465&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in &lt;f712f98eb8e445c8918edaf595bbe465&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in &lt;f712f98eb8e445c8918edaf595bbe465&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in &lt;f712f98eb8e445c8918edaf595bbe465&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in &lt;f712f98eb8e445c8918edaf595bbe465&gt;:0 
  at Kudu.Core.Deployment.DeploymentManager+&lt;Build&gt;d__35.MoveNext () [0x005aa] in &lt;2d2f67d4d9ca4ebdb0d017f393081a49&gt;:0 " /><!-- duration: 14ms -->
    </step><!-- duration: 3676ms -->
```

**Comment by nickwalkmsft** [comment]
We are tracking this [here](https://github.com/Azure-App-Service/kudu/issues/9). Thanks for reporting.
