### ISSUE TITLE
WebHooks Manager does not validate the URL passed in via the Web Hook.

### ISSUE THREAD

**Issue by FinVamp1** [projectkudu/kudu#2392]
If there is no URL in the JSON for the WebHook then a URI Exception can bring down the process when the WebHook is triggered.

E.G.

RegisterServices() at C:\Kudu Files\Private\src\master\Kudu.Services.Web\App_Start\NinjectServices.cs:194

System.UriFormatException: Invalid URI: The URI is empty.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Uri..ctor(String uriString)

   at Kudu.Core.Hooks.WebHooksManager.CreateHttpClient(WebHook webHook)

   at Kudu.Core.Hooks.WebHooksManager.<PublishToHookAsync>d__17.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Kudu.Core.Hooks.WebHooksManager.<PublishToHooksAsync>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Kudu.Core.Hooks.WebHooksManager.<>c__DisplayClass14_0.<<PublishEventAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Kudu.Contracts.Infrastructure.LockExtensions.<LockOperationAsync>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Kudu.Core.Hooks.WebHooksManager.<PublishEventAsync>d__14.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Kudu.Core.Jobs.TriggeredJobsManager.<ReportTriggeredJobFinished>d__15.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

I've put in some protection in the PR that's coming but you may have a more elegant way to fix this.

**Comment by FinVamp1** [comment]
This is my simple way of checking this before running the Web Hook. [https://github.com/projectkudu/kudu/pull/2393](PR 2393)
