### ISSUE TITLE
/deploy webhook: works from local machine, errors from giltab-ci.yml

### ISSUE THREAD

**Issue by MayasHaddad** [projectkudu/kudu#2451]
I cautiously followed these [steps](https://christianliebel.com/2016/05/auto-deploying-to-azure-app-services-from-gitlab/)

The only difference I have with this tutorial is that I want to trigger deploy after gitlab "lint->test->build" pipeline succeeds.
 
I Ran [this](https://github.com/projectkudu/kudu/wiki/Manually-triggering-a-deployment#raw-post) on my local machine :

1. I get `401 - Unauthorized: Access is denied due to invalid credentials.` when I provide get publish profile credentials, but a `200` and deploy proceeds without incident when I provide deployment credentials
2. when, however, gitlab pipeline runs ~the very same~ curl command that succeeds I get this cryptic stacktrace:
```xml
<step title="Error occurred" date="2017-05-29T22:40:47.937" type="error" text="Request failed with status code: 401" stackTrace="   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)
   at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger, ITracer tracer)
   at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass10_1.&lt;&lt;ProcessRequestAsync&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Contracts.Infrastructure.LockExtensions.&lt;LockOperationAsync&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Services.FetchHandler.&lt;ProcessRequestAsync&gt;d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)" />
    <!-- duration: 16ms -->
```

Any clue? Am I doing something wrong?

**Comment by MayasHaddad** [comment]
As for `2.` it turns out url in the payload was not correctly evaluated, so the credentials were wrong.

But for `1.` I still get the `401`

**Comment by davidebbo** [comment]
If you go to https://{yourapp}.scm.azurewebsites.net/basicauth, are you able to use the publish profile creds?

**Comment by MayasHaddad** [comment]
Yes it worked.

I found out that the username in gitlab secret variables needed to have an extra `$` at the beginning, otherwise it's eval-ed as empty string.
