### ISSUE TITLE
Race condition in start continuous webjobs after site startup caused job runner not found.

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2484]
Start continuous webjobs right after job startup races with jobs initialization leading to job runner not found.  

```
Error occurred type="error" text="Missing job runner for an existing job - #######" stackTrace="   at Kudu.Core.Jobs.ContinuousJobsManager.EnableJob(String jobName)
   at Kudu.Services.Jobs.JobsController.EnableContinuousJob(String jobName)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
