### ISSUE TITLE
Concurrent PUT /functions causes file in used issue

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2486]
We should either synchronize all put or simply 409 not support concurrent PUTs at all (clear and simple).

```
Error occurred type="error" text="The process cannot access the file 'D:\home\site\wwwroot\NuGet.Config' because it is being used by another process." stackTrace="   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Abstractions.FileWrapper.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Kudu.Core.Infrastructure.FileSystemHelpers.<WriteAllTextToFileAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Functions.FunctionManager.<CreateOrUpdateAsync>d__6.MoveNext()
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
