### ISSUE TITLE
NullRefException when deploying from BitBucket

### ISSUE THREAD

**Issue by michimune** [projectkudu/kudu#2493]
### Repro steps.
This issue only occurs when deploying from BitBucket. We are still not sure about the complete repro steps, but according to Nick's theory, the issue occurs when a deployment from a deleted branch on BitBucket is requested.

### The log/error given by the failure.
Object reference not set to an instance of an object." stackTrace="   at Kudu.Services.ServiceHookHandlers.BitbucketHandlerV2.<>c__DisplayClass1_0.<GetDeploymentInfo>b__0(JToken change)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Kudu.Services.ServiceHookHandlers.BitbucketHandlerV2.GetDeploymentInfo(JObject payload, String targetBranch)
   at Kudu.Services.ServiceHookHandlers.BitbucketHandlerV2.TryParseDeploymentInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo& deploymentInfo)
   at Kudu.Services.FetchHandler.GetRepositoryInfo(HttpRequestBase request, JObject payload, String targetBranch, DeploymentInfo& info)
   at Kudu.Services.FetchHandler.<ProcessRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

### Mention any other details that might be useful.
Nick already found the following from the BitBucket webhook body schema:

new: An object containing information about the state of the reference after the push. When a branch is deleted, new is null.

**Comment by michimune** [comment]
Nick's comment: this issue can occur not from a deleted branch. It can occur if a repo contains a deleted branch.
