### ISSUE TITLE
Should recover from "The payload was invalid. Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl" exception

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2555]
500 consistently returns from listsecret api.   Suggestion is to auto-recover from this.

```csharp
Error occurred type="error" text="The payload was invalid." stackTrace="
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Kudu.Core.Infrastructure.SecurityUtility.DecryptSecretString(String content)
   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Functions.FunctionController.<GetSecrets>d__12.MoveNext()
```

Internal Ref:
```
union cluster('wawswus').database('wawsprod').Kudu,
cluster('wawscus').database('wawsprod').Kudu,
cluster('wawseus').database('wawsprod').Kudu,
cluster('wawseas').database('wawsprod').Kudu,
cluster('wawsneu').database('wawsprod').Kudu,
cluster('wawsweu').database('wawsprod').Kudu
| where PreciseTimeStamp > datetime(2017-09-07)
| where PreciseTimeStamp < datetime(2017-09-08)
| where EventId == 65514
| where Message contains "The payload was invalid"  
| summarize count() by siteName
```

**Comment by watashiSHUN** [comment]
https://github.com/projectkudu/kudu/blob/bb683db7bb748aaa49d1e062c59f1258e0827166/Kudu.Core/Functions/FunctionManager.cs#L184-L189
since we were able to extract key string from the json file, which implies that the file corruption is unlikely, above function does not do extra error handling.

this error could be caused by manual editing of the key, I could add a `catch` and `throw` to give a better message, and it will be filtered as `400` instead of `500`

**Comment by suwatch** [comment]
That sounds good.

**Comment by watashiSHUN** [comment]
https://github.com/projectkudu/kudu/commit/94fccd0c4d4607fe5c1076b9aef0f1d588a27061
