### ISSUE TITLE
Installing SiteExtension interrupted leaving corrupted nupkg

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2594]
Installing SiteExtension could be interrupted (eg. site restart).   This may leave nupkg in corrupted state.  Corrently, there is no way to recover besides manually d:\home\SiteExtensions\{name} and reinstall.  The fix would be to make it idempotent and retryable.   We could consider putting pending (or mark as pending) marker to signify that this wasn't installed completely and allow reinstalling.   Get siteextensions should not return those in pending state.

RE: 2 customer reported incidents around the time this issue was opened. 

```csharp
Error occurred type="error" text="Unable to read package from path 'Microsoft.ApplicationInsights.AzureWebSites\Microsoft.ApplicationInsights.AzureWebSites.2.4.3.nupkg'." stackTrace="
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.Client.V2.VisualStudio.V2SearchLatestResource.<>c__DisplayClass3.<<Search>b__0>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Client.V2.VisualStudio.V2SearchLatestResource.<Search>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.SiteExtensions.FeedExtensions.<Search>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.SiteExtensions.SiteExtensionManager.<GetLocalExtensions>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.SiteExtensions.SiteExtensionController.<GetLocalExtensions>d__8.MoveNext()
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
