### ISSUE TITLE
Unable to update/install application insights site extension

### ISSUE THREAD

**Issue by xt0rted** [projectkudu/kudu#2606]
One of my sites indicated that there was a new version of the app insights extension available so I tried to update it. Upon clicking update I received an error saying a file was in use and it couldn't update and then the extension disappeared from the list of installed extensions. Now each time I try to reinstall the extension I get the following error.

```
Failed to install Application Insights - System.IO.DirectoryNotFoundException:
 Could not find a part of the path 'D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\Runtime'.
  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
  at System.IO.Abstractions.DirectoryWrapper.Delete(String path, Boolean recursive)
  at Kudu.Core.Infrastructure.FileSystemHelpers.MoveDirectory(String sourceDirName, String destDirName)
  at Kudu.Core.SiteExtensions.SiteExtensionManager.<>c__DisplayClass27_1.b__1()
  at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.b__0()
  at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
  at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)
  at Kudu.Core.SiteExtensions.SiteExtensionManager.EnsureInstallationEnviroment(String installationDir, ITracer tracer)
  at Kudu.Core.SiteExtensions.SiteExtensionManager.d__26.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__25.MoveNext()
```

I tried to update the extension through the SCM site, not the portal.

**Comment by davidebbo** [comment]
Does it help if you stop the site first? Also, you can try manually deleting the `D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites` folder from Kudu Console. And if that fails, it would be interesting to use Kudu Process Explorer to check what might have a handle locking it,

/cc @iusafaro

**Comment by xt0rted** [comment]
I checked `D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites` and there was a `SiteExtensionStatus.json` in it with the same error I first reported. I then restarted the site and tried installing again. This time it installed ok.

Once the extension was installed I couldn't browse to `xxxxx.scm.azurewebsites.net/ApplicationInsights/` without first restarting the SCM site.

Everything seems to be working now.

**Comment by davidebbo** [comment]
> Once the extension was installed I couldn't browse to xxxxx.scm.azurewebsites.net/ApplicationInsights/ without first restarting the SCM site.

This part is normal, as the application.xdt needs a restart to take effect.

**Comment by xt0rted** [comment]
I just ran into this issue on another site. The first error after clicking update is

```
Failed to update Application Insights - System.IO.IOException:
 The process cannot access the file 'D:\home\SiteExtensions\Microsoft.ApplicationInsights.AzureWebSites\Instrumentation32\ProductionBreakpoints_x86.dll' because it is being used by another process.
 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
 at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
 at System.IO.Abstractions.FileWrapper.OpenWrite(String path)
 at Kudu.Core.SiteExtensions.FeedExtensions.d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 t Kudu.Core.SiteExtensions.SiteExtensionManager.d__27.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Kudu.Core.SiteExtensions.SiteExtensionManager.d__26.MoveNext()
```

Once the site is restarted the app insights extension can be reinstalled.

**Comment by xt0rted** [comment]
I went through and updated the rest of my sites, they all produced the same error and needed to be restarted and the extension reinstalled.

**Comment by xt0rted** [comment]
This looks to have been resolved with https://github.com/projectkudu/kudu/pull/2621. I haven't had an issue updating any of my AI site extensions in recent months.
