### ISSUE TITLE
Error improvement when SiteExtension installation failed due to Nuget related

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2615]
Suggestion: convert this to 409 or 400.

```csharp
The process cannot access the file 'D:\\home\\SiteExtensions\\Microsoft.ApplicationInsights.AzureWebSites\\Microsoft.ApplicationInsights.AzureWebSites.2.4.5.nupkg' because it is being used by another process."
,"ExceptionType":"System.IO.IOException","StackTrace":"   
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
    at NuGet.PhysicalFileSystem.OpenFile(String path)
    at NuGet.OptimizedZipPackage.EnsureManifest()
    at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
    at NuGet.LocalPackageRepository.OpenPackage(String path)
    at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
    at NuGet.LocalPackageRepository.<GetPackages>d__15.MoveNext()
    at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
    at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
    at NuGet.LocalPackageRepository.FindPackagesById(String packageId)
    at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
    at NuGet.Client.V2.VisualStudio.V2UIMetadataResource.<>c__DisplayClass11.<GetMetadata>b__d()
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at NuGet.Client.V2.VisualStudio.V2UIMetadataResource.<GetMetadata>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Kudu.Core.SiteExtensions.FeedExtensions.<GetLatestPackageByIdFromMetaRes>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Kudu.Core.SiteExtensions.FeedExtensions.<GetLatestPackageByIdFromSrcRepo>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Kudu.Core.SiteExtensions.SiteExtensionManager.<GetLocalExtension>d__23.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at Kudu.Services.SiteExtensions.SiteExtensionController.<GetLocalExtension>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"} (HTTP InternalServerError)System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
    at System.Net.HttpWebRequest.GetResponse()
    at Microsoft.Web.Hosting.Administration.Csm.Common.Clients.GeoClientBase.GetResponse[T](HttpWebRequest request, Boolean reThrowOnHostUnavailability, HttpStatusCode[] 
```

**Comment by suwatch** [comment]
All were caused by the race condition with background SiteExtension installation.   User performed SiteExtensions installation from portal and Kudu launched a BG task.  While BG task was downloading the nuget package, the poll GetSiteExtension request from Portal arrived leading to the issue.  The least invasive fix is to return 409 and Portal will retry polling.

```
WAWSWEU
Kudu
| where PreciseTimeStamp > datetime(2017-11-10 03:40)
| where PreciseTimeStamp < datetime(2017-11-10 03:50)
| where Tenant == "977fdb98e7b243c9b51df6c3fab7cba9" 
| where RoleInstance == "WebWorkerRole_IN_3" 
| project PreciseTimeStamp, siteName, verb, statusCode, address, Message, userAgent, RoleInstance   
```

**Comment by davidebbo** [comment]
I see, good find. And it seems both the download and the read access that fails live within NuGet logic that we don't control. So best we can do is catch the IO exception and turn it into 409?

**Comment by suwatch** [comment]
Thinking more about this, let's say if we look at SiteExtensionController.GetLocalExtension api in isolation.   Caller calls to get the local siteextension info to check its installation status as in #2615, #2594 and partially #2606.   

  - The call may return 404 if the installation process hasn't started yet (see log query above)). 
  - The call may fail if download nupkg is on-going (nupkg file is in use).   Or, in theory, it could fail if nupkg file is corrupted (along the same line as invalid xml for deployment settings xml).     

If we just want to patch and move on, yes let's do 409 specifically for file in use error.   If we want to treat all GetLocalSiteExtension failure (invalid or corrupted nupkg) the same way, perhaps catch all and convert to 404 (as if initially not exist default state).   We will return exception message as well as log it accordingly regardless.   Thought?

In the future, given all opened issues mentioned were related to Microsoft.ApplicationInsights.AzureWebSites extension, assuming it is commonly used, we could consider promote it to be a builtin extension (similar to phpmyadmin).
