### ISSUE TITLE
Kudu throws IO exceptions when listing WebJobs directories

### ISSUE THREAD

**Issue by Nking92** [projectkudu/kudu#2655]
Kudu doesn't catch file system exceptions when listing files in the WebJobs directories. The uncaught exception propagates all the way to the WebJobs blade in the Azure Portal, which seems to use Kudu APIs to list the files. There was a CRI where the WebJobs blade was broken by this type of exception. See ICM incident 55356272 for details.

### Repro steps.
Create some situation where listing the webjobs output directories will result in an IO exception. This originally happened due to a corrupted storage volume.

### The log/error given by the failure.
{"Code":"InternalServerError","Message":"{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"The file or directory is corrupted and unreadable.\\r\\n\",\"ExceptionType\":\"System.IO.IOException\",\"StackTrace\":\"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\\r\\n   at System.IO.FileSystemEnumerableIterator`1.MoveNext()\\r\\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\\r\\n   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.Abstractions.DirectoryInfoWrapper.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetJobRunsDirectories(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetLatestJobRun(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.UpdateJob(TriggeredJob job)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.BuildJob(DirectoryInfoBase jobDirectory, Boolean nullJobOnError)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobsInternal()\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobs(Boolean forceRefreshCache)\\r\\n   at Kudu.Services.Jobs.JobsController.ListAllJobs()\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"}","Target":null,"Details":[{"Message":"{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"The file or directory is corrupted and unreadable.\\r\\n\",\"ExceptionType\":\"System.IO.IOException\",\"StackTrace\":\"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\\r\\n   at System.IO.FileSystemEnumerableIterator`1.MoveNext()\\r\\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\\r\\n   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.Abstractions.DirectoryInfoWrapper.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetJobRunsDirectories(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetLatestJobRun(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.UpdateJob(TriggeredJob job)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.BuildJob(DirectoryInfoBase jobDirectory, Boolean nullJobOnError)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobsInternal()\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobs(Boolean forceRefreshCache)\\r\\n   at Kudu.Services.Jobs.JobsController.ListAllJobs()\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"}"},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":"{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"The file or directory is corrupted and unreadable.\\r\\n\",\"ExceptionType\":\"System.IO.IOException\",\"StackTrace\":\"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\\r\\n   at System.IO.FileSystemEnumerableIterator`1.MoveNext()\\r\\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\\r\\n   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at System.IO.Abstractions.DirectoryInfoWrapper.GetDirectories(String searchPattern, SearchOption searchOption)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetJobRunsDirectories(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.GetLatestJobRun(String jobName)\\r\\n   at Kudu.Core.Jobs.TriggeredJobsManager.UpdateJob(TriggeredJob job)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.BuildJob(DirectoryInfoBase jobDirectory, Boolean nullJobOnError)\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobsInternal()\\r\\n   at Kudu.Core.Jobs.JobsManagerBase`1.ListJobs(Boolean forceRefreshCache)\\r\\n   at Kudu.Services.Jobs.JobsController.ListAllJobs()\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"}"}}],"Innererror":null}

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by davidebbo** [comment]
Adding more readable stack

```
The file or directory is corrupted and unreadable

System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 at System.IO.FileSystemEnumerableIterator1.MoveNext()
 at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
 at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
 at System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)
 at System.IO.Abstractions.DirectoryInfoWrapper.GetDirectories(String searchPattern, SearchOption searchOption)
 at Kudu.Core.Jobs.TriggeredJobsManager.GetJobRunsDirectories(String jobName)
 at Kudu.Core.Jobs.TriggeredJobsManager.GetLatestJobRun(String jobName)
 at Kudu.Core.Jobs.TriggeredJobsManager.UpdateJob(TriggeredJob job)
 at Kudu.Core.Jobs.JobsManagerBase1.BuildJob(DirectoryInfoBase jobDirectory, Boolean nullJobOnError)
 at Kudu.Core.Jobs.JobsManagerBase1.ListJobsInternal()
 at Kudu.Core.Jobs.JobsManagerBase1.ListJobs(Boolean forceRefreshCache)
 at Kudu.Services.Jobs.JobsController.ListAllJobs()
```

Though it's debatable what should happen in this case. If the API can't read the file system, it needs to fail.
