### ISSUE TITLE
function app error (captured in log stream) when creating a function with function api manager

### ISSUE THREAD

**Issue by kastwey** [projectkudu/kudu#2692]
### Repro steps.
1. Create a function app (consumption or app, the result is the same).
2. Attach to log stream (i'm using az client).
```
az webapp log tail --resource-group <resourcegroup> --name <name>
3. Create a function with function manager api. The json I'm sending is:
```json
{
  "config": {
    "bindings": [
      {
        "type": "timerTrigger",
        "direction": "in",
        "name": "timer",
        "schedule": "0 */3 * * * *"
      }
    ]
  },
  "files": {
    "run.csx": "#r \"System.Net.Http\"\r\n#r \"Newtonsoft.Json\"\r\n#r \"..\\shared\\AZFunctionsShared.dll\"\r\nusing System;\r\nusing System.Threading;\r\nusing System.Threading.Tasks;\r\nusing Newtonsoft.Json;\r\nusing System.Net;\r\nusing System.Net.Http;\r\nusing System.Net.Http.Headers;\r\nusing System.Collections.Generic;\r\nusing AZFunctionsShared;\r\n\r\n\r\npublic static async Task Run(TimerInfo timer, TraceWriter log)\r\n{\r\n\r\n    var content = new StringContent(\"{\\\"Name\\\":\\\"Juanjo\\\",\\\"LastName\\\":\\\"Montiel\\\"}\", System.Text.Encoding.UTF8, \"application/json\");\r\n\tawait SharedLibrary.ApiCallerClient.PostAsync(\"http://somedir.azurewebsites.net/api/MeasureFunctionExecution/?functionName=test152&interval=3\", content);\r\n    log.Info(\"Called http://somedir.azurewebsites.net/api/MeasureFunctionExecution/?functionName=test152&interval=3 with data {\\\"Name\\\":\\\"Juanjo\\\",\\\"LastName\\\":\\\"Montiel\\\"}\");\r\n}"
  }
}
```

The result returned is 
HTTP/1.1 201 Created

And the function is present in file system and is executed.
However, in the log stream, I see:
2018-02-10T12:45:35    Error occurred, type: error, text: Function (test152) config does not exist or is invalid, stackTrace:    at Kudu.Core.Functions.FunctionManager.<GetFunctionConfigAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Functions.FunctionController.<Get>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-02-10T12:45:35    Outgoing response, type: response, statusCode: 404, statusText: Not Found, Server: Microsoft-IIS/10.0, x-ms-request-id: 284b54ec-48a0-4181-8b6a-772ea8c2ec2a, Cache-Control: private, X-AspNet-Version: 4.0.30319, Content-Type: application/json; charset=utf-8

The function is create successfully and runs... but if I try to create, for example, 300 trigger functions with this API, the previous created functions runs slow (if I scheduled them each three minutes, during other functions creation this time may increase up to five or six minutes).
Even in one of my tests, while creating functions with the API, the application ended up blocking and the functions do not longer executed, but I don't know if the above error may be causing the application to stop responding or is another strange thing.

Regards,

Juanjo.

**Comment by watashiSHUN** [comment]
A quick look at functionController https://github.com/projectkudu/kudu/blob/1c964466b760e367c34da9026cbfa24f089f6681/Kudu.Services/Functions/FunctionController.cs#L63-L76 it seems that if there's an issue during creation, Kudu will not return `HttpStatusCode.Created`

The error you are seeing could be caused by other APIs (which justify why the function still runs) ie: simply try to get function.json
https://github.com/projectkudu/kudu/blob/1c964466b760e367c34da9026cbfa24f089f6681/Kudu.Services/Functions/FunctionController.cs#L95-L100
maybe it was called when function is not fully created? I not am sure, but if you can [share you app name](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) I can take a look at the logs

**Comment by kastwey** [comment]
Hi,

I just discovered the error reason.
Before create a function, I check if it exists or not, calling to /api/function/function_name.
This call (in case of function does not exists) is which causes the error. I thought that managed exceptions would not appear on the console :$
Is it normal a call to /api/function/non_existing_function causes the mentioned error? Could this error cause some kind of instability in the container?

If yes, What is the best way to determine whether a function exists?
IN order to avoid error, I'm getting a function list and check if the function name exists inside results, but this operation spends more time tan call to function  endpoind directly and check status code.

Thanks!

**Comment by davidebbo** [comment]
Seems like a bug that it returns an error. But still, the http code is 404, no? That should be enough to tell you it doesn't exist.

**Comment by kastwey** [comment]
Yes, of course. In fact, it is I was doing. I only want to know if this error might cause a system unstability (and for now is better to use the function list), or the error does not matter and I can continue using the function endpoint to determine if it exists.

Thanks for your quick response!

**Comment by davidebbo** [comment]
It is ugly, but will not cause instability.

**Comment by watashiSHUN** [comment]
there is another option: you can use file system api:

> https://{webapp_name}.scm.azurewebsites.net/api/vfs/site/wwwroot/{function_name}/function.json

it will return 404, and kudu will not append exception:

https://github.com/projectkudu/kudu/blob/1c964466b760e367c34da9026cbfa24f089f6681/Kudu.Services/Infrastructure/VfsControllerBase.cs#L62

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
