### ISSUE TITLE
Internal Kudu errors during site extension installation via arm

### ISSUE THREAD

**Issue by pakrym** [projectkudu/kudu#2697]
We are currently testing ASP.NET Core site extensions and have seen a bunch of site extension deployment failures that do not seem to be connected to the template or it's arguments.

[Template](https://gist.githubusercontent.com/pakrym/f22f813806b8d42c1ac212904b562d20/raw/44be04e126e6d029313a51497c2c0bbd17ec7fc0/AspNetCore.template.json)

# 1
**AspNetCoreVersion**: 2.1.0-preview1-28275

Fails during deployment of Microsoft.AspNetCore.AzureAppServices.SiteExtension

Full error JSON:

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"id\": \"/subscriptions/6de210d0-cc8d-4f7e-ba0b-295f894b0638/resourcegroups/anurse-verification/providers/Microsoft.Web/sites/anurse-verification-site/siteextensions/Microsoft.AspNetCore.AzureAppServices.SiteExtension\",\r\n \"name\": \"anurse-verification-site/Microsoft.AspNetCore.AzureAppServices.SiteExtension\",\r\n \"type\": \"Microsoft.Web/sites/siteextensions\",\r\n \"location\": \"West US 2\",\r\n \"properties\": {\r\n \"id\": \"Microsoft.AspNetCore.AzureAppServices.SiteExtension\",\r\n \"title\": null,\r\n \"type\": \"Gallery\",\r\n \"summary\": null,\r\n \"description\": null,\r\n \"version\": null,\r\n \"extension_url\": null,\r\n \"project_url\": null,\r\n \"icon_url\": null,\r\n \"license_url\": null,\r\n \"feed_url\": null,\r\n \"authors\": null,\r\n \"installer_command_line_params\": null,\r\n \"published_date_time\": null,\r\n \"download_count\": 0,\r\n \"local_is_latest_version\": null,\r\n \"local_path\": null,\r\n \"installed_date_time\": null,\r\n \"provisioningState\": \"Failed\",\r\n \"comment\": \"System.InvalidOperationException: Stack empty.\\r\\n at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\\r\\n at System.Collections.Generic.Stack`1.Pop()\\r\\n at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)\\r\\n at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)\\r\\n at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)\\r\\n at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)\\r\\n at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()\\r\\n at System.ComponentModel.Composition.Primitives.Export.get_Value()\\r\\n at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)\\r\\n at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()\\r\\n at System.Lazy`1.CreateValue()\\r\\n at System.Lazy`1.LazyInitValue()\\r\\n at System.Lazy`1.get_Value()\\r\\n at NuGet.Client.SourceRepository.<GetResourceAsync>d__8`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at NuGet.Client.SourceRepository.<GetResourceAsync>d__5`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at Kudu.Core.SiteExtensions.FeedExtensions.<GetResourceAndValidateAsync>d__6`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at Kudu.Core.SiteExtensions.FeedExtensions.<GetPackageByIdentity>d__3.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\\r\\n at Kudu.Core.SiteExtensions.SiteExtensionManager.<TryInstallExtension>d__26.MoveNext()\"\r\n }\r\n}"}]}
```

I parsed the stack trace out here:
```
System.InvalidOperationException: Stack empty.
 at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
 at System.Collections.Generic.Stack1.Pop()
 at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
 at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
 at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
 at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
 at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
 at System.ComponentModel.Composition.Primitives.Export.get_Value()
 at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
 at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_02.<CreateStronglyTypedLazyOfTM>b__1()
 at System.Lazy1.CreateValue()
 at System.Lazy1.LazyInitValue()
 at System.Lazy1.get_Value()
 at NuGet.Client.SourceRepository.<GetResourceAsync>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Client.SourceRepository.<GetResourceAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Kudu.Core.SiteExtensions.FeedExtensions.<GetResourceAndValidateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Kudu.Core.SiteExtensions.FeedExtensions.<GetPackageByIdentity>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Kudu.Core.SiteExtensions.SiteExtensionManager.<TryInstallExtension>d__26.MoveNext()
```
/cc @anurse

# 2
```
<step title="Error occurred" date="2018-02-13T18:14:21.474" type="error" text="
D:\Program Files (x86)\SiteExtensions\Kudu\70.10205.3242\bin\Scripts\starter.cmd &quot;D:\home\site\deployments\tools\deploy.cmd&quot;" stackTrace="
   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command, String message)" />
            <!-- duration: 0ms -->
            <step title="Purge deployment items" date="2018-02-13T18:14:21.553" >
                <step title="Remove cbc02b04a, Failed, received at 2/13/2018 6:06:36 PM" date="2018-02-13T18:14:21.585" />
                <!-- duration: 0ms -->
            </step>
            <!-- duration: 32ms -->
        </step>
        <!-- duration: 39387ms -->
        <step title="Error occurred" date="2018-02-13T18:14:21.601" type="error" text="
D:\Program Files (x86)\SiteExtensions\Kudu\70.10205.3242\bin\Scripts\starter.cmd &quot;D:\home\site\deployments\tools\deploy.cmd&quot;" stackTrace="
   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command, String message)
   at Kudu.Core.Deployment.Generator.GeneratorSiteBuilder.Build(DeploymentContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Deployment.DeploymentManager.&lt;Build&gt;d__36.MoveNext()" />
        <!-- duration: 0ms -->
    </step>
```
/cc @brennanconroy

**Comment by davidebbo** [comment]
Can you try serizaling the two extension installations (using dependsOn)? I wonder if they issues come from them running in parallel.

**Comment by pakrym** [comment]
# 3
```
{
  "error": {
    "code": "InternalServerError",
    "message": "There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: ff609f31-9e11-4956-b182-0e920db29f2d"
  }
}
```

**Comment by pakrym** [comment]
I updated template to have `dependsOn` between site extensions

**Comment by davidebbo** [comment]
Can you share the test Web App name, and the UTC time of the failure?

**Comment by pakrym** [comment]
@davidebbo I added more information for # 3 in the comment above.

**Comment by davidebbo** [comment]
Looks like the failure is in the serverfarm, before it even gets to the site. If so, none of what you have under Microsoft.Web/sites is relevant, and the same would repro with a minimal template.

**Comment by davidebbo** [comment]
Closing here as this is not related to Kudu, and we are now discussing internally.

**Comment by davidebbo** [comment]
Though as I look at your original error, that one was site extension related, and maybe that one would have been addressed by the `dependsOn`. But then you hit that unrelated condition when you retried.
