### ISSUE TITLE
Function triggers won't synchronize if host.json has comments

### ISSUE THREAD

**Issue by ConnorMcMahon** [projectkudu/kudu#2712]
PostDeploymentHelper.SyncFunctionTriggers uses JavascriptSerializer.cs, which doesn't support comments in JSON. This makes the synchronize triggers action fail if the JSON has comments, which some customers have been doing. This is a little harsh, so we should use Newtonsoft to do our parsing in this case.

We see an exception like one of the ones below in the Kudu logs if this happens:

```
Error occurred type="error" text="Invalid JSON primitive: ." stackTrace="
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Kudu.Core.Helpers.PostDeploymentHelper.GetTaskHub(JavaScriptSerializer serializer, String hostConfigPath)
   at Kudu.Core.Helpers.PostDeploymentHelper.<SyncFunctionsTriggers>d__23.MoveNext()  
```

or 

```
System.ArgumentException: Invalid object passed in, ':' or '}' expected: {
	"tracing": {
		"consoleLevel": "verbose"
	},
	//evil comments
}
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Kudu.Core.Helpers.PostDeploymentHelper.GetTaskHub(JavaScriptSerializer serializer, String hostConfigPath)
   at Kudu.Core.Helpers.PostDeploymentHelper.<SyncFunctionsTriggers>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Deployment.DeploymentManager.<Build>d__36.MoveNext()
```

**Comment by davidebbo** [comment]
Root of the issue is that we use `JavaScriptObjectDeserializer` instead of Newtonsoft in Kudu's postdeploymenthelper.cs, and that doesn't tolerate comment (it's stricter json). @suwatch / @EricSten-MSFT I seem to recall that the reason was that this helper needed to be used by msdeploy, and for some reason msdeploy couldn't use Newtonsoft. Do you recall?

Also, I think the issue was made worse with #2659 for durable. Previously, it was only reading function.json, but now it also reads host.json. So some scenarios where it was working became broken, /cc @tohling.

Though the root issue is the deserializer being too strict.

**Comment by suwatch** [comment]
Given multiple versions of NewtonSoft to deal with and our limited usage scope, we went with the framework-provided  `JavaScriptObjectSerializer` for dependency simplicity.

As for `json comment`, it is not provisioned in http://www.json.org/ spec.   Many serializer won't understand it (jsonviewer for instance).    Even with newtonsoft, it can only read (simply ignore those) but never write it as far as I know.

Is the json comment commonly added by our tooling (portal or CLI) or user simply handcrafted the JSON assuming it to work?

**Comment by davidebbo** [comment]
It's mostly likely added randomly by users manually editing the file.

We cannot change the runtime to reject it as it's a major breaking change. So our best option is to somehow allow Kudu to support them. Both the runtime and scale controller support them (because they both use Newtonsoft).

Some options:

1. Switch to Newtonsoft
2. Strip comments ourselves, e.g. using some hack like [this](https://stackoverflow.com/a/31681009/111888)

**Comment by davidebbo** [comment]
Here is maybe a better sample to strip comments: https://stackoverflow.com/a/3524689/111888

**Comment by aklefdal** [comment]
Instead of changing the serialisation in SyncFunctionTriggers, could we instead give some really visible warning in the runtime?

**Comment by suwatch** [comment]
After discussing with @EricSten-MSFT, we decided to go with a straight forward solution - using NewtonSoft.Json.dll.   This will make us consistent across.   The caveat is an additional dependency (Newtonsoft.Json.dll) required to call PostDeploymentHelper and, possibly, proper assembly binding/redirect.   

At this moment, both callers (Kudu and MSDeploy) are using same Newtonsoft.Json.dll 9.0.0.0 version.
