### ISSUE TITLE
Getting "409 There is a deployment currently in progress" when there is no deployment in progress

### ISSUE THREAD

**Issue by ashmind** [projectkudu/kudu#2834]
### Repro steps.
This AppVeyor build: https://ci.appveyor.com/project/ashmind/sharplab/build/master-14 is failing.
I'm deploying to `sharplab-edge` using a ZIP deployment.
This site was previously using Git deployment, which worked.
This is the first try to implement a ZIP deployment -- it never worked yet.

My first attempt failed with:
```
System.InvalidOperationException
    at Kudu.Core.SourceControl.NullRepository.GetChangeSet(String id) in C:\Kudu Files\Private\src\master\Kudu.Core\SourceControl\NullRepository.cs:line 70
    at Kudu.Core.Deployment.FetchDeploymentManager.<PerformDeployment>d__9.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 235
....
```
(see full exception here: https://ci.appveyor.com/project/ashmind/sharplab/build/master-12)

I disconnected site from GitHub after that, and tried again -- getting 409 now:
```
Error performing Zip Push Deploy (409 status): There is a deployment currently in progress. Please try again when it completes.
```

However there is no deployment running (according to https://sharplab-edge.scm.azurewebsites.net/api/deployments).

### Project structures.
Seems to be related to state of the site, but the repo is here:
https://github.com/ashmind/SharpLab

And AppVeyor build is doing this:
```
sl.bat setup
dotnet restore source/WebApp/WebApp.csproj
dotnet msbuild source/WebApp/WebApp.csproj /p:Configuration=Release /p:UnbreakablePolicyReportEnabled=false /t:Publish /verbosity:minimal
powershell -Command "Compress-Archive -Path source/WebApp/bin/publish/* -DestinationPath source/WebApp/bin/publish/WebApp.zip"
```

Then uses build-in AppVeyor AzureAppServiceZipDeploy to push WebApp.zip.

### The log/error given by the failure.
```
Error performing Zip Push Deploy (409 status): There is a deployment currently in progress. Please try again when it completes.
```

### Debug your Azure website remotely.
My site is sharplab-edge, deployments are at https://sharplab-edge.scm.azurewebsites.net/api/deployments. This is a testing site, so feel free to start/stop/delete files if you need to investigate.

**Comment by ashmind** [comment]
Hmmm, nevermind, it started working by itself now.
