### ISSUE TITLE
NullReferenceException in SyncTriggers API when parsing simple function.json

### ISSUE THREAD

**Issue by cgillum** [projectkudu/kudu#2908]
### Repro steps.
1. Create a v2 consumption function app in Azure
2. Create a C# script timer-trigger function as described in the official docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#c-script-example

**run.csx**
```csharp
public static void Run(TimerInfo myTimer, ILogger log)
{
    if(myTimer.IsPastDue)
    {
        log.LogInformation("Timer is running late!");
    }
    
    log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now:o}" );  
}
```
**function.json**
```json
{
    "schedule": "*/30 * * * * *",
    "name": "myTimer",
    "type": "timerTrigger",
    "direction": "in"
}
```

3. Create a semi-empty host.json file.
```json
{
    "version": "2.0"
}
```
4. Call the SyncTriggers API

### Project structures
```
D:\home\site\wwwroot\FastTimer
D:\home\site\wwwroot\host.json
D:\home\site\wwwroot\FastTimer\function.json
D:\home\site\wwwroot\FastTimer\run.csx
```

### The log/error given by the failure.
```xml
<step title="Incoming Request" date="2018-11-12T20:45:51.659" instance="f713f0" url="/api/functions/synctriggers" method="POST" type="request" pid="9456,2,7" Connection="Keep-Alive" Content-Length="0" Authorization="Bas..." Host="cgillum-func.scm.cgillum-westus.antares-test.windows-int.net" X-WAWS-Unencoded-URL="/api/functions/synctriggers" CLIENT-IP="131.107.174.201:28436" X-ARR-LOG-ID="ee3008af-769b-4a82-96f0-ed517c09945c" X-SITE-DEPLOYMENT-ID="cgillum-func" WAS-DEFAULT-HOSTNAME="cgillum-func.scm.cgillum-westus.antares-test.windows-int.net" X-Forwarded-Proto="https" >
    <step title="Cleanup Xml Logs" date="2018-11-12T20:45:51.722" />
    <!-- duration: 63ms -->
    <step title="FunctionController.SyncTriggers" date="2018-11-12T20:45:51.864" >
        <step title="D:\home\site\wwwroot\FastTimer\function.json is invalid. System.NullReferenceException: Object reference not set to an instance of an object.
   at Kudu.Core.Helpers.PostDeploymentHelper.DeserializeFunctionTrigger(String functionJson) in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 414" date="2018-11-12T20:45:52.081" />
        <!-- duration: 47ms -->
    </step>
    <!-- duration: 342ms -->
    <step title="Error occurred" date="2018-11-12T20:45:52.333" type="error" text="Object reference not set to an instance of an object." stackTrace="   at Kudu.Core.Helpers.PostDeploymentHelper.DeserializeFunctionTrigger(String functionJson) in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 437
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;&gt;c.&lt;SyncFunctionsTriggers&gt;b__28_1(String f) in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 165
   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;SyncFunctionsTriggers&gt;d__28.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Functions.FunctionController.&lt;SyncTriggers&gt;d__16.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Functions\FunctionController.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.&lt;CastToObject&gt;d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" />
    <!-- duration: 47ms -->
    <step title="Outgoing response" date="2018-11-12T20:45:52.505" type="response" statusCode="500" statusText="Internal Server Error" Server="Microsoft-IIS/10.0" x-ms-request-id="ee3008af-769b-4a82-96f0-ed517c09945c" Cache-Control="private" X-AspNet-Version="4.0.30319" Content-Type="application/json; charset=utf-8" />
    <!-- duration: 31ms -->
</step>
<!-- duration: 971ms -->
```

**Comment by cgillum** [comment]
I looked at the code and the issue is that I didn't have a `"bindings"` array in my function.json (the docs are confusing in this regard). I think one improvement we could make here is to add a friendlier error message and avoid the NullReferenceException.

**Comment by suwatch** [comment]
Thanks Chris!

It is [this line](https://github.com/projectkudu/kudu/blob/8958f17953b10db3d35a649091daab1d3c72e87b/Kudu.Core/Helpers/PostDeploymentHelper.cs#L415) and potentially [this line](https://github.com/projectkudu/kudu/blob/8958f17953b10db3d35a649091daab1d3c72e87b/Kudu.Core/Helpers/PostDeploymentHelper.cs#L418).  

@ahmelsayed / @balag0   could you robust this up?

**Comment by balag0** [comment]
Yes we need something like
https://github.com/Azure/azure-functions-host/blame/18537bdb30ca0915bf362a32dd935f39ae222932/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L171

**Comment by suwatch** [comment]
Sounds good  - throw a more readable message.  

To recap, bindings and type are required for function.json - lacking of will cause failure in syntrigger (and post deployment).  Since the fix is the error message improvement class, we can categorize as low pri (not urgent).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
