### ISSUE TITLE
App Fails when deploying through Azure Pipelines but not VSCode

### ISSUE THREAD

**Issue by simkessy** [projectkudu/kudu#2992]
I built a node js app and it runs locally no problem

I used the VSCode App Service Extension to deploy and that works fine as well. 

I then tried to set up DevOps to deploy using Pipelines and this is where things are failing for me. 
When I deploy using Pipelines the logs give me this error: 

```
Documentation: http://aka.ms/webapp-linux
NodeJS quickstart: https://aka.ms/node-qs
NodeJS Version : v8.11.4
Generating app startup command
Found scripts.start in /home/site/wwwroot/package.json
Running npm --prefix=/home/site/wwwroot start
> app@1.0.0 start /home/site/wwwroot
> npm run serve

2019-06-10T18:01:36.515701963Z Debugger listening on ws://0.0.0.0:49494
For help see https://nodejs.org/en/docs/inspector
module.js:549
    throw err;
    ^
Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/site/wwwroot/node_modules/.bin/npm:19:21
2019-06-10T18:01:36.888554937Z     at Object.<anonymous> (/home/site/wwwroot/node_modules/.bin
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 start: `npm run serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 start script.
2019-06-10T18:01:37.008807919Z npm ERR! This is probably not a problem with npm. There is likely
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-10T18_01_36_958Z-debug.log
```

Folder Structure: 

![image](https://user-images.githubusercontent.com/5871660/59374564-fb786a80-8d00-11e9-9364-59b86ba43d5a.png)

Package build scripts: 

```
"scripts": {
    "start": "npm run serve",
    "serve": "node dist/index.js",
    "prebuild": "tslint -c tslint.json -p tsconfig.json --fix 'src/**/*'",
    "build": "tsc",
    "dev": "nodemon --exec ts-node src\\index.ts",
    "d": "nodemon -r esm src\\index.ts",
    "check-types": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

Pipelines setup: 

![image](https://user-images.githubusercontent.com/5871660/59374642-2793eb80-8d01-11e9-9dc6-21c5de291c31.png)

But yea it's just not working for some reason.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
