### ISSUE TITLE
Fail fast if unable to release the lock stream

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3004]
There was a corner case where we attempted to [take a file lock](https://github.com/projectkudu/kudu/blob/4016b77f9d3ef2a537dac83b09c9a3e29b0e7851/Kudu.Core/Infrastructure/LockFile.cs#L144-L197) but failed after we already opened a stream.    In finally, we attempt to close - however, if the close failed, we may leave the stream open (lock) without way to recover.   We should try to fail fast in this case.   

```csharp
StartJob() at C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:151
System.IO.IOException: The network name cannot be found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Kudu.Core.Infrastructure.LockFile.Lock(String operationName) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\LockFile.cs:line 194
   at Kudu.Core.Jobs.ContinuousJobRunner.TryGetLockIfSingleton(Boolean& acquired) in C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:line 236
   at Kudu.Core.Jobs.ContinuousJobRunner.<>c__DisplayClass22_0.<StartJob>b__0() in C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:line 96
```

**Comment by suwatch** [comment]
Also this stack.

```csharp
StartJob() at C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:151
System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Kudu.Core.Infrastructure.LockFile.Lock(String operationName) in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\LockFile.cs:line 192
   at Kudu.Core.Jobs.ContinuousJobRunner.TryGetLockIfSingleton(Boolean& acquired) in C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:line 236
   at Kudu.Core.Jobs.ContinuousJobRunner.<>c__DisplayClass22_0.<StartJob>b__0() in C:\Kudu Files\Private\src\master\Kudu.Core\Jobs\ContinuousJobRunner.cs:line 96
```
