### ISSUE TITLE
POST /api/zipdeploy failing with "Missing content-type boundary"

### ISSUE THREAD

**Issue by jeffnicholson-arcurve** [projectkudu/kudu#3006]
zipdeploy via `POST /api/zipdeploy` to a Linux App Service is failing, error is related to "Missing content-type boundary".  
This was working as of yesterday (16-07-2019).  
Relevant snip of stack trace (full trace below):  
```
Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Kudu.Services.MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit) in /tmp/KuduLite/Kudu.Services/Util/MultipartRequestHelper.cs:line 17
   at Kudu.Services.FileStreamingHelper.StreamFile(HttpRequest request, Stream targetStream) in /tmp/KuduLite/Kudu.Services/Util/FileStreamingHelper.cs:line 29
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ZipDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 225
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeploy(Boolean isAsync, String author, String authorEmail, String deployer, String message) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 94
```

### Repro
With PowerShell, follow Example 2 from https://github.com/projectkudu/kudu/wiki/REST-API#sample-of-using-rest-api-with-powershell:
```
$username = "`$website"
$password = "pwd"
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $password)))
$userAgent = "powershell/1.0"

# Example 2: call the zipdeploy API (which uses POST)
$apiUrl = "https://{sitename}.scm.azurewebsites.net/api/zipdeploy"
$filePath = "C:\Temp\foo.zip"
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST -InFile $filePath -ContentType "multipart/form-data"
```
The zip file is a packaged web app, which was previously deployed successfully via zipdeploy.

### Error
Request fails with a `500`:
`Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.`

The kudu trace logs show an exception:
```
2019-07-17T13:26:49  Startup Request, url: /api/zipdeploy, method: POST, type: request, pid: 72,1,4, ScmType: None
2019-07-17T13:26:51    Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Kudu.Services.MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit) in /tmp/KuduLite/Kudu.Services/Util/MultipartRequestHelper.cs:line 17
   at Kudu.Services.FileStreamingHelper.StreamFile(HttpRequest request, Stream targetStream) in /tmp/KuduLite/Kudu.Services/Util/FileStreamingHelper.cs:line 29
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ZipDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 225
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeploy(Boolean isAsync, String author, String authorEmail, String deployer, String message) in /tmp/KuduLite/Kudu.Services/Deployment/PushDeploymentController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 53
2019-07-17T13:26:51      Error occurred, type: error, text: Missing content-type boundary., stackTrace:    at Microsoft.AspNetCore.Http.Features.FormFeature.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 53
```

**Comment by jeffnicholson-arcurve** [comment]
Also opened issue in the KuduLite repo, https://github.com/Azure-App-Service/KuduLite/issues/70. If that is sufficient this can be closed.

**Comment by blitzxion** [comment]
This is also occurring for App Services using docker+linux. I'm getting the exact same error and pretty much the same stack trace.

**Comment by jeffnicholson-arcurve** [comment]
Closing in favor of https://github.com/Azure-App-Service/KuduLite/issues/70, this is a Kudu Lite issue.
After disabling Kudu Lite in the App Service Application Settings with `ENABLE_KUDU_LITE = false` deploying via zip deploy worked.
