### ISSUE TITLE
Zip Deploy - Thread was being aborted

### ISSUE THREAD

**Issue by MattJeanes** [projectkudu/kudu#3032]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
**NOTE: Intermittent issue**
- Create azure function app
- Use Kudu web deploy feature through Publish-AzWebApp Az Powershell command
- Cmdlet reports success but deployment actually failed due to some kind of timeout, issue visible on https://xxxx.scm.azurewebsites.net/ZipDeployUI
- No functions are showing or running in azure portal, wwwroot folder is empty
- Retry Publish-AzWebApp command
- Now successfully completes and functions are showing and working correctly in Azure portal

### Project structures.
N/A - any function app

### The log/error given by the failure.
Diagnostic data dump - LogFiles\kudu\trace\xxx_api-zipdeploy_pending.xml shows error
```
<step title="BackgroundTrace" date="2019-09-13T09:39:43.994" instance="a5417f" url="/api/zipdeploy" method="POST" >
  <step title="Creating temporary deployment" date="2019-09-13T09:39:44.873" /><!-- duration: 76ms -->
  <step title="Performing fetch based deployment" date="2019-09-13T09:39:44.965" >
    <step title="Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\z3so34ts.zip (10.21 MB) to D:\local\Temp\zipdeploy\extracted" date="2019-09-13T09:39:45.201" >
      <step title="Extracting 158 entries to D:\local\Temp\zipdeploy\extracted directory" date="2019-09-13T09:39:45.231" >
        <step title="Extracting to D:\local\Temp\zipdeploy\extracted\bin\MyApp.Azure.Functions.dll ..." date="2019-09-13T09:39:45.246" /><!-- duration: 0ms -->
        <step title="Extracting to D:\local\Temp\zipdeploy\extracted\bin\MyApp.Azure.Functions.pdb ..." date="2019-09-13T09:39:45.246" /><!-- duration: 16ms -->
        <step title="Extracting to D:\local\Temp\zipdeploy\extracted\bin\MyApp.DataStore.dll ..." date="2019-09-13T09:39:45.261" /><!-- duration: 377ms -->
        <step title="Extracting to D:\local\Temp\zipdeploy\extracted\bin\MyApp.DataStore.dll.config ..." date="2019-09-13T09:39:45.656" /><!-- duration: 0ms -->
        <step title="Extracting to D:\local\Temp\zipdeploy\extracted\bin\MyApp.DataStore.pdb ..." date="2019-09-13T09:39:45.656" /><!-- duration: 12ms -->
        <step title="Omitting extracting file traces ..." date="2019-09-13T09:39:45.683" /><!-- duration: 16ms -->
        <step title="Error occurred" date="2019-09-13T09:39:46.889" type="error" text="Thread was being aborted." stackTrace="   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_1.&lt;PerformBackgroundDeployment&gt;b__3() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 339
   at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 34
   at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 46
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_0.&lt;PerformBackgroundDeployment&gt;b__1() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 323" /><!-- duration: 0ms -->
      </step><!-- duration: 1673ms -->
    </step><!-- duration: 1720ms -->
```

### Mention any other details that might be useful.
The main issue I have with this, though I appreciate it may not be your area is that Azure itself reports that the publish was successful even though it failed. If it threw an error it wouldn't be so bad as it could be retried and the failure would be known but this could do undetected for a while potentially.

Thank you

**Comment by suwatch** [comment]
First to answer why Task was cancelled. The site config was updated 10s before the deployment started.   Site config could take upto 10-15 sec to propagate to site and causing site to restart.  This delay config change propagation terminated the deployment process.  It should not show as successful deployment, however.

**Comment by MattJeanes** [comment]
Hi thank you, yes that would make sense.

I'm creating / updating site settings and then immediately pushing a zip deploy via a powershell script to deploy some functions. What do you recommend? I'm currently working around by querying the Azure functions api to list the functions for the function app and if there isn't any it means the deploy failed and to retry.

As for the deployment showing as successful on the api is this something you guys will deal with or do I need to raise an issue on Azure directly?

**Comment by suwatch** [comment]
Put a delay between update and zip deploy say 30s to be safe.  To see if deployment is successful, you should query /api/deployments.

**Comment by MattJeanes** [comment]
@suwatch I'll look into that api, thanks - if it is coming back as successful even for a failed deployment I'll let you know. I'll close this issue until then at least - cheers, really appreciate it
