### ISSUE TITLE
Deploy AzureFunctions ends with "Thread was being aborted"

### ISSUE THREAD

**Issue by dlyson** [projectkudu/kudu#3086]
I'm running a deployment from Azure Devops with a zip package. I explicitly set the Deployment method to `Zip Deploy` as the `auto-detect` option made other errors for me. The deployment succeeds the first time, but fails in each next attempt. 

Log of the first try (success):
```
2019-12-02T10:03:44.4157982Z ##[section]Starting: Deploy Functions
2019-12-02T10:03:44.4317160Z ==============================================================================
2019-12-02T10:03:44.4317304Z Task         : Azure Functions
2019-12-02T10:03:44.4317401Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2019-12-02T10:03:44.4317511Z Version      : 1.158.0
2019-12-02T10:03:44.4317581Z Author       : Microsoft Corporation
2019-12-02T10:03:44.4317682Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2019-12-02T10:03:44.4317783Z ==============================================================================
2019-12-02T10:03:45.3884641Z Got service connection details for Azure App Service:'myapp-raf-eus2-functions'
2019-12-02T10:03:46.0579232Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"0"}
2019-12-02T10:03:46.0579802Z Deleting App Service Application settings. Data: ["WEBSITE_RUN_FROM_ZIP"]
2019-12-02T10:04:07.8979150Z Package deployment using ZIP Deploy initiated.
2019-12-02T10:04:32.3804973Z Deploy logs can be viewed at https://myapp-raf-eus2-functions.scm.azurewebsites.net/api/deployments/747c5560764a44cb95fded4b43866d13/log
2019-12-02T10:04:32.3805570Z Successfully deployed web package to App Service.
2019-12-02T10:04:34.7117904Z Successfully updated App Service configuration details
2019-12-02T10:04:35.5252272Z Successfully added release annotation to the Application Insight : myapp-raf-eus2-appInsights
2019-12-02T10:04:35.9486104Z Successfully updated deployment History at https://myapp-raf-eus2-functions.scm.azurewebsites.net/api/deployments/8911575281075508
2019-12-02T10:04:36.3561698Z App Service Application URL: http://myapp-raf-eus2-functions.azurewebsites.net
2019-12-02T10:04:47.4801185Z ##[section]Finishing: Deploy Functions
```

Second try (failure):
```
2019-12-02T10:09:41.7053869Z ##[section]Starting: Deploy Functions
2019-12-02T10:09:41.7172738Z ==============================================================================
2019-12-02T10:09:41.7172855Z Task         : Azure Functions
2019-12-02T10:09:41.7172963Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2019-12-02T10:09:41.7173064Z Version      : 1.158.0
2019-12-02T10:09:41.7173128Z Author       : Microsoft Corporation
2019-12-02T10:09:41.7173378Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2019-12-02T10:09:41.7173472Z ==============================================================================
2019-12-02T10:09:42.7478211Z Got service connection details for Azure App Service:'myapp-raf-eus2-functions'
2019-12-02T10:09:43.8462541Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"0"}
2019-12-02T10:09:43.8462919Z Deleting App Service Application settings. Data: ["WEBSITE_RUN_FROM_ZIP"]
2019-12-02T10:09:45.0997498Z Package deployment using ZIP Deploy initiated.
2019-12-02T10:09:59.8576837Z Updating submodules.
2019-12-02T10:09:59.8577111Z Preparing deployment for commit id '91497efd13'.
2019-12-02T10:09:59.8577342Z Generating deployment script.
2019-12-02T10:10:00.1952063Z Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
2019-12-02T10:10:00.1952619Z Running deployment command...
2019-12-02T10:10:00.3909448Z Command: "D:\home\site\deployments\tools\deploy.cmd"
2019-12-02T10:10:00.3909765Z Handling Basic Web Site deployment.
2019-12-02T10:10:00.3909976Z Creating app_offline.htm
2019-12-02T10:10:00.3910161Z KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
2019-12-02T10:10:00.3910366Z Deleting app_offline.htm
2019-12-02T10:10:00.3910531Z Finished successfully.
2019-12-02T10:10:00.3910719Z Running post deployment command(s)...
2019-12-02T10:10:00.3910929Z Triggering recycle (preview mode disabled).
2019-12-02T10:10:00.3911680Z D:\home\site\wwwroot\MyFunction\function.json is invalid. System.Threading.ThreadAbortException: Thread was being aborted.\r\n   at Microsoft.Win32.Win32Native.GetFileType(SafeFileHandle handle)\r\n   at Microsoft.Win32.Win32Native.SafeCreateFile(String lpFileName, Int32 dwDesiredAccess, FileShare dwShareMode, SECURITY_ATTRIBUTES securityAttrs, FileMode dwCreationDisposition, Int32 dwFlagsAndAttributes, IntPtr hTemplateFile)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)\r\n   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)\r\n   at System.IO.File.ReadAllText(String path)\r\n   at Kudu.Core.Helpers.PostDeploymentHelper.DeserializeFunctionTrigger(String functionJson) in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 409
2019-12-02T10:10:00.3976375Z ##[error]Failed to deploy web package to App Service.
2019-12-02T10:10:00.3986251Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2019-12-02T10:10:01.1541562Z Successfully added release annotation to the Application Insight : myapp-raf-eus2-appInsights
2019-12-02T10:10:01.4926898Z Successfully updated deployment History at https://myapp-raf-eus2-functions.scm.azurewebsites.net/api/deployments/8911575281401140
2019-12-02T10:10:01.6646472Z App Service Application URL: http://myapp-raf-eus2-functions.azurewebsites.net
2019-12-02T10:10:01.6878789Z ##[section]Finishing: Deploy Functions
```

The details of failure are:
```
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.Win32.Win32Native.GetFileType(SafeFileHandle handle)
   at Microsoft.Win32.Win32Native.SafeCreateFile(String lpFileName, Int32 dwDesiredAccess, FileShare dwShareMode, SECURITY_ATTRIBUTES securityAttrs, FileMode dwCreationDisposition, Int32 dwFlagsAndAttributes, IntPtr hTemplateFile)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Kudu.Core.Helpers.PostDeploymentHelper.DeserializeFunctionTrigger(String functionJson) in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 409
```
another deploy and the log looks like follows:
```
2019-12-02T11:42:32.8087399Z Syncing 13 function triggers with payload size 1965 bytes failed with System.Threading.ThreadAbortException: Thread was being aborted.
   at Kudu.Core.Helpers.PostDeploymentHelper.<PostAsync>d__40.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 497
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Kudu.Core.Helpers.PostDeploymentHelper.PostAsync(String path, String requestId, String content)
   at Kudu.Core.Helpers.PostDeploymentHelper.<SyncFunctionsTriggers>d__30.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 205
2019-12-02T11:42:32.8146162Z ##[error]Failed to deploy web package to App Service.
```
When I restart the app in Azure Poral then it is restarted without failured.

I deploy Function App v2 with .net core code. It's using a consumption plan in eastus2.
Kudu details:
Build 85.11108.4192.0 (279f924bdc)
Azure App Service 86.0.7.55 (master-8a4720a38bb)

**Comment by suwatch** [comment]
It seemed like you rely on VSTS to perform Site Config update and, subsequently, deployment.  The issue is Site Config update (eg. appSettings) is asynchronous in nature - meaning even the VSTS call completes successfully - there is a pending restart on the web app.  This pending restart could interrupt/abort the on-going deployment.  

The workaround is to avoid VSTS to perform any Config update - instead put all your desired configuration in ARM template.

**Comment by dlyson** [comment]
I'm not sure if I understand the answer. My deployment consists a couple of steps in AzureDevops. One of the first steps is apply changes to resources via ARM template (it updates the appSettings). Then I have another step that deploys the azure functions code and this step fails. 
I tried another time and attach the traces from kudu. File `2019-12-03T08-50-57_92d5e9_003_Background_POST_api-zipdeploy_2s.xml` contains a failure.
[logfiles_kudu_trace.zip](https://github.com/projectkudu/kudu/files/3915969/logfiles_kudu_trace.zip)

**Comment by dlyson** [comment]
I think now I understand your answer. We explicitly added the `WEBSITE_RUN_FROM_PACKAGE=1` setting to the applicaiton settings via ARM (previous task in the pipeline). Then the task _Azure Functions_ completes with success. Probably because it does not need to update the config.
