### ISSUE TITLE
REST API zipdeploy with packageUri fails when WEBSITE_RUN_FROM_PACKAGE=1

### ISSUE THREAD

**Issue by kamilzzz** [projectkudu/kudu#3255]
### Repro steps.
1. Add WEBAPP_RUN_FROM_PACKAGE = 1 appsetting
2. Trigger zipdeploy through api

Deploying code:
```csharp
var deploymentRequest = new HttpRequestMessage(HttpMethod.Put, $"https://{webApp.Name}.scm.azurewebsites.net/api/zipdeploy");
deploymentRequest.Headers.Authorization = new AuthenticationHeaderValue("Basic", token);
deploymentRequest.Content = new StringContent(JsonSerializer.Serialize(new
{
    packageUri = "<url>"
}), Encoding.UTF8, "application/json");
```

### Project structures.
Standard ASP.NET Core app.

### The log/error given by the failure.
```
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at Kudu.Services.Deployment.PushDeploymentController.WriteSitePackageZip(ZipDeploymentInfo zipDeploymentInfo, ITracer tracer)
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ZipDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context)
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeployViaUrl(JObject requestJson, Boolean isAsync, Boolean syncTriggers, Boolean overwriteWebsiteRunFromPackage, String author, String authorEmail, String deployer, String message)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Mention any other details that might be useful.

WebApp is using Linux plan.

**Comment by suwatch** [comment]
@purva-vasudeo  could you help with this Kudu on Linux?

**Comment by purva-vasudeo** [comment]
The setting for run from package is WEBSITE_RUN_FROM_PACKAGE=1. I noticed you are using in the repro steps. Can you confirm?

**Comment by BBergquist** [comment]
I am seeing the same issue, @purva-vasudeo. In my case, I am using "WEBSITE_RUN_FROM_PACKAGE". My deployment code is different though: I am using an ARM template with the ZipDeploy extension subresource.

**Comment by cbodin** [comment]
I've been struggling with the same error and figured out the problem by checking the azure-cli source code. The `az webapp deployment source config-zip` command uses the same kudu zip deploy api. However, it adds some additional headers:
https://github.com/Azure/azure-cli/blob/b88d627d0d681d97639df452c47266a31ed6f3b0/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L595-L600C74

By including those i get a successful deployment. The full command:
```shell
curl -D - \
     --fail-with-body \
     -X POST \
     -H "Content-Type: application/octet-stream" \
     -H "Cache-Control: no-cache" \
     -u '<username:password>' \
     -T "<filename.zip>" \
     "https://<app-service-name>.scm.azurewebsites.net/api/zipdeploy"
```

Replace `<username>:<password>`, `<filename.zip>` and `<app-service-name>`.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
