### ISSUE TITLE
Local Zip handler: Central directory corrupt 

### ISSUE THREAD

**Issue by MichaelKx** [projectkudu/kudu#3407]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------
### Repro steps.
> your project built successfully on your dev machine but failed on Azure? : yes
> please write down your build tools and their versions: MSBuild version 17.3.1+2badb37d1 for .NET

### Problem description
Build runs successfully on buildenvironment. Generating Zip file, Upload to functionhost via Post request to Zipdeploy.uri (https://<name>.scm.azurewebsites.net/api/zipdeploy)
We get back a status code Ok. Then Kudu has incoming request with post 500 and executes Zip-pushdeploy => this ones fails than with error message: 
 <step title="Error occurred" date="2022-10-11T09:47:20.607" type="error" text="Central Directory corrupt." stackTrace="   at Kudu.Services.Deployment.PushDeploymentController.&lt;LocalZipHandler&gt;d__17.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 559

### kudu trace logfile:
`<step title="Incoming Request" date="2022-10-11T09:47:16.458" instance="5db74a" url="/api/zipdeploy" method="POST" type="request" ......(xxxx)
  <step title="ZipPushDeploy" date="2022-10-11T09:47:16.880" >
    <step title="Functions App ZipDeploy. Run from package." date="2022-10-11T09:47:16.927" />
    <step title="Starting PushDeployAsync" date="2022-10-11T09:47:17.021" />
    <step title="Updating shutdown sentinel last write time" date="2022-10-11T09:47:17.208" SemaphoreCount="7" />
    <step title="LockFile &apos;D:\home\site\locks\deployments.lock&apos; acquired" date="2022-10-11T09:47:17.286" />
    <step title="Saving request content to D:\home\data\SitePackages\20221011094716.zip" date="2022-10-11T09:47:17.380" >
      <step title="Total 0 bytes written to D:\home\data\SitePackages\20221011094716.zip" date="2022-10-11T09:47:17.427" />
    </step>
    <step title="Deleting outdated zip file D:\home\data\SitePackages\20221006154119.zip" date="2022-10-11T09:47:17.552" />
    <step title="LockFile &apos;D:\home\site\locks\deployments.lock&apos; released" date="2022-10-11T09:47:17.692" />
    <step title="Deleting shutdown sentinel file" date="2022-10-11T09:47:17.802" SemaphoreCount="8" />
    <step title="Starting FetchDeploy" date="2022-10-11T09:47:17.864" />
    <step title="Attempting to fetch target branch HEAD" date="2022-10-11T09:47:17.974" />
    <step title="Updating shutdown sentinel last write time" date="2022-10-11T09:47:18.239" SemaphoreCount="7" />
    <step title="LockFile &apos;D:\home\site\locks\deployments.lock&apos; acquired" date="2022-10-11T09:47:18.317" />
    <step title="Performing fetch based deployment" date="2022-10-11T09:47:18.396" >
      <step title="Creating temporary deployment" date="2022-10-11T09:47:18.427" />
      <step title="Fetching changes." date="2022-10-11T09:47:19.279" />
      <step title="Starting LocalZipHandler" date="2022-10-11T09:47:19.419" />
      <step title="Starting ExtractTriggers" date="2022-10-11T09:47:19.482" />
      <step title="Central Directory corrupt. DEPLOYMENTINFO: deploymentPath = Functions App ZipDeploy. Run from package., deployer = ZipDeploy, os = windows, sku = ElasticPremium, language = dotnet-isolated, siteName = <sitename>‌, slotName = Production, siteHostName = <sitename>‌.azurewebsites.net, deploymentStatus = Error" date="2022-10-11T09:47:19.638" />
    </step>
    <step title="LockFile &apos;D:\home\site\locks\deployments.lock&apos; released" date="2022-10-11T09:47:20.310" />
    <step title="Deleting shutdown sentinel file" date="2022-10-11T09:47:20.451" SemaphoreCount="8" />
  </step>
  <step title="Error occurred" date="2022-10-11T09:47:20.607" type="error" text="Central Directory corrupt." stackTrace="   at Kudu.Services.Deployment.PushDeploymentController.&lt;LocalZipHandler&gt;d__17.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 559
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;PerformDeployment&gt;d__9.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;PerformDeployment&gt;d__9.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 296
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass8_0.&lt;&lt;FetchDeploy&gt;b__0&gt;d.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Contracts.Infrastructure.LockExtensions.&lt;LockOperationAsync&gt;d__7`1.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;FetchDeploy&gt;d__8.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Deployment.PushDeploymentController.&lt;PushDeployAsync&gt;d__15.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 441
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Deployment.PushDeploymentController.&lt;ZipPushDeploy&gt;d__11.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.&lt;CastToObject&gt;d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" innerText="An attempt was made to move the file pointer before the beginning of the file.
" innerStackTrace="   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()" />
  <step title="Outgoing response" date="2022-10-11T09:47:20.888" type="response" statusCode="500" statusText="Internal Server Error" Server="Microsoft-IIS/10.0" x-ms-request-id="d36e42ad-3b16-4e7b-abdd-e9d476bfa407" Cache-Control="private" X-AspNet-Version="4.0.30319" Content-Type="application/json; charset=utf-8" />
</step>
`

> ---------------------------------------------------------------

**Comment by patelchandni** [comment]
Hi @MichaelKx, using which tool did you build and generate the zip file? 
Did you try to redeploy the same zip file? What was the result of redeployment?

**Comment by MichaelKx** [comment]
Hi @patelchandni,
we re-deloyed the zip, but same issue. 
Build with .net SDK 6.0.401 with .net publish (uses MS-build version 17.3.1+2badb37d1 in background).

After the build we generate the function zip file with the following comment:
"C:\Program Files\7-Zip\7z.exe" a -tZip -r ${bamboo.build.working.directory}\function.zip ${bamboo.build.working.directory}\source\bin\Release\net6.0\publish\*

The function.zip is then send via a POST request to the zipdeploy uri.

Thanks for your support!

**Comment by patelchandni** [comment]
@MichaelKx, from which tool did you build you project like VS code, visual studio, core tools, DevOps? 
Can you please create .zip file using built-in .zip compression manually and then re-deploy?

**Comment by JacksonSc** [comment]
Hi @patelchandni,
the tools installed on build server:
- Visual Studion Build Tool 2022
- .NET Core SDK 6.0.401
The build itself is then executed in a bamboo agent which executes shell script. 
The build script is 
"C:\Program Files\dotnet\dotnet.exe" restore --no-cache
"C:\Program Files\dotnet\dotnet.exe" publish -c Release

Then the a shell script is executed to create the zip - file:
"C:\Program Files\7-Zip\7z.exe" a -tZip -r ${bamboo.build.working.directory}\function.zip ${bamboo.build.working.directory}\source\bin\Release\net6.0\publish\*

As additional info:
The problem occurs randomly and we can therefore not always reproduce.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
