### ISSUE TITLE
Azure functions are not started after Post zipdeploy

### ISSUE THREAD

**Issue by MichaelKx** [projectkudu/kudu#3408]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
your project built successfully on your dev machine but failed on Azure? : yes
please write down your build tools and their versions: MSBuild version 17.3.1+2badb37d1 for .NET

### Problem description
Azure functions are not started after Post zipdeploy

###Error Message: 
 <step title="End HttpPost, status: 0" date="2022-10-11T13:15:26.003" />
  <step title="Syncing function triggers by calling the functions runtime site failed. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;PostAsync&gt;d__49.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 671 ....

###Logs Kudu trace log (BackgroundTrace)
`<step title="BackgroundTrace" date="2022-10-11T13:09:12.617" instance="5db74a" url="synctriggers-operation" method="POST" >
  <step title="Cleanup Xml Logs" date="2022-10-11T13:09:12.648" />
  <step title="Updating shutdown sentinel last write time" date="2022-10-11T13:09:12.726" SemaphoreCount="6" />
  <step title="Delaying &apos;00:01:00&apos; for Functions site to restart." date="2022-10-11T13:09:12.789" />
  <step title="Begin HttpPost <url>‌, x-ms-request-id: 62a79f23-0481-4714-a486-15d8eef4c9a7" date="2022-10-11T13:10:16.408" />
  <step title="End HttpPost, status: 0" date="2022-10-11T13:11:56.619" />
  <step title="Begin HttpPost <url>‌, x-ms-request-id: 62a79f23-0481-4714-a486-15d8eef4c9a7" date="2022-10-11T13:12:01.192" />
  <step title="End HttpPost, status: 0" date="2022-10-11T13:13:41.309" />
  <step title="Begin HttpPost <url>‌, x-ms-request-id: 62a79f23-0481-4714-a486-15d8eef4c9a7" date="2022-10-11T13:13:45.908" />
  <step title="End HttpPost, status: 0" date="2022-10-11T13:15:26.003" />
  <step title="Syncing function triggers by calling the functions runtime site failed. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;PostAsync&gt;d__49.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 671
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;&gt;c__DisplayClass38_1.&lt;&lt;TryFunctionsRuntimeSyncTriggers&gt;b__1&gt;d.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Infrastructure.OperationManager.&lt;&gt;c__DisplayClass4_0.&lt;&lt;AttemptAsync&gt;b__0&gt;d.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Kudu.Core.Infrastructure.OperationManager.&lt;AttemptAsync&gt;d__5`1.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Infrastructure\OperationManager.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Helpers.PostDeploymentHelper.&lt;TryFunctionsRuntimeSyncTriggers&gt;d__38.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Helpers\PostDeploymentHelper.cs:line 302" date="2022-10-11T13:15:26.081" />
  <step title="Attempting to perform settriggers call directly." date="2022-10-11T13:15:26.195" />
  <step title="Begin HttpPost <url./opreations/settriggers>‌, x-ms-request-id: 62a79f23-0481-4714-a486-15d8eef4c9a7" date="2022-10-11T13:15:29.810" />
  <step title="End HttpPost, status: OK" date="2022-10-11T13:15:32.774" />
  <step title="Syncing 0 function triggers with payload size 15 bytes successful." date="2022-10-11T13:15:32.841" />
  <step title="Deleting shutdown sentinel file" date="2022-10-11T13:15:32.903" SemaphoreCount="8" />
</step>
`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
