### ISSUE TITLE
KuduScript repo is obsolete and misleading

### ISSUE THREAD

**Issue by aawalton** [projectkudu/kudu#3479]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> your project built successfully on your dev machine but failed on Azure?
> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

<details>
<summary><h2>What we're trying to accomplish.</h2></summary>

We're migrating a complex production server from Heroku to Azure App Service.

We're unable to use the standard build automation for the following reasons.

1. We've standardized on `yarn` instead of `npm`.
1. The standard build automation using npm install.
1. While yarn and npm have a similar interface, there are enough differences that our repo will not build correctly with npm install.

</details>

<details>
<summary><h2>Why we're using a custom Kudu deployment script.<h2></summary>

We started with the Azure docs [here](https://learn.microsoft.com/en-us/azure/app-service/configure-language-nodejs?pivots=platform-linux#customize-build-automation).

We then followed the link to the Oryx configuration [here](https://github.com/microsoft/Oryx/blob/main/doc/configuration.md).

While the Oryx configuration supports a `CUSTOM_BUILD_COMMAND`, we've found no evidence of a parallel `CUSTOM_INSTALL_COMMAND`. Since we need a custom install command, we can't use the standard build automation.

We then following the link to the Azure deployment docs [here](https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli#enable-build-automation-for-zip-deploy).

From there we went to the Kudu documentation [here](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url). This lead to the docs for taking over the deployment [here](https://github.com/projectkudu/kudu/wiki/Configurable-settings#take-over-the-whole-deployment-script), which lead to the Customizing deployments document [here](https://github.com/projectkudu/kudu/wiki/Customizing-deployments).

While learning more about Kudu, we found the Kudu custom script generator instructions [here](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script). 

Using the command `kuduscript -y --node` to generate a deployment script was mostly successful, with the exception of `selectNodeVersion` failing on deploy.
</details>

### Project structures.
> in order to reproduce your issue at our end we need a simple 
> [github repository](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)
> that highlights structure of the project

<details>
<summary><h2>How we created the reproduction repo<h2></summary>
[Current commit for reproduction repo](https://github.com/latitudegames/latitude-api-test/tree/7b96b9808350d2b1a9bb6fb105a562c171ac6fb4)

1. Initialized a new repo with a README from GitHub.
2. `yarn init`
3. Added empty `yarn.lock`
4. `yarn install`
5. `kuduscript -y --node`
</details>

<details>
<summary><h2>How we created the azure app service.</h2></summary>
Created a new Azure App Service for Linux instance with default settings except the following.
1. Selected Node 16 LTS runtime stack (Node 18 LTS also appears to be affected)
2. Turned on GitHub Actions Workflow (which added the deployment workflow and publishing profile env vars to the repo).
</details>

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

<details>
<summary><h2>Specific error messages.</h2></summary>

```bash
Run azure/webapps-deploy@v2
  with:
    app-name: latitude-api-test
    slot-name: Production
    publish-profile: ***
    package: .
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '367bce[2](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:2)9-2'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
Running custom deployment command...
Not setting execute permissions for bash deploy.sh
Running deployment command...
Command: bash deploy.sh
Handling node.js deployment.
Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
Ignoring: .deployment
Copying file: '.gitignore'
Copying file: '.pnp.cjs'
Copying file: '.pnp.loader.mjs'
Copying file: 'README.md'
Ignoring: deploy.sh
Copying file: 'package-lock.json'
Copying file: 'package.json'
Copying file: 'yarn.lock'
Ignoring: .git
Copying file: '.github/workflows/main_latitude-api-test.yml'
Copying file: '.yarn/install-state.gz'
Copying file: 'node_modules/.package-lock.json'
Copying file: 'node_modules/.bin/prebuild-install'
Copying file: 'node_modules/.bin/rc'
Copying file: 'node_modules/.bin/semver'
Copying file: 'node_modules/b4a/LICENSE'
Copying file: 'node_modules/b4a/README.md'
Copying file: 'node_modules/b4a/browser.js'
Copying file: 'node_modules/b4a/index.js'
Copying file: 'node_modules/b4a/package.json'
Copying file: 'node_modules/b4a/lib/ascii.js'
Copying file: 'node_modules/b4a/lib/base64.js'
Copying file: 'node_modules/b4a/lib/hex.js'
Copying file: 'node_modules/b4a/lib/utf16le.js'
Copying file: 'node_modules/b4a/lib/utf8.js'
Copying file: 'node_modules/base64-js/LICENSE'
Copying file: 'node_modules/base64-js/README.md'
Copying file: 'node_modules/base64-js/base64js.min.js'
Copying file: 'node_modules/base64-js/index.d.ts'
Copying file: 'node_modules/base64-js/index.js'
Copying file: 'node_modules/base64-js/package.json'
Copying file: 'node_modules/bl/.travis.yml'
Copying file: 'node_modules/bl/BufferList.js'
Copying file: 'node_modules/bl/LICENSE.md'
Copying file: 'node_modules/bl/README.md'
Copying file: 'node_modules/bl/bl.js'
Copying file: 'node_modules/bl/package.json'
Copying file: 'node_modules/bl/test/convert.js'
Copying file: 'node_modules/bl/test/indexOf.js'
Copying file: 'node_modules/bl/test/isBufferList.js'
Copying file: 'node_modules/bl/test/test.js'
Copying file: 'node_modules/buffer/AUTHORS.md'
Copying file: 'node_modules/buffer/LICENSE'
Copying file: 'node_modules/buffer/README.md'
Copying file: 'node_modules/buffer/index.d.ts'
Copying file: 'node_modules/buffer/index.js'
Copying file: 'node_modules/buffer/package.json'
Copying file: 'node_modules/chownr/LICENSE'
Omitting next output lines...
/opt/Kudu/Scripts/selectNodeVersion.js:166
    throw new Error('Unable to locate node.js installation directory at ' + nodejsDir);
    ^

Error: Unable to locate node.js installation directory at /opt/nodejs
    at Object.<anonymous> (/opt/Kudu/Scripts/selectNodeVersion.js:166:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:[3](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:3)2)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:[4](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:4)7
An error has occurred during web site deployment.
select node version failed
/opt/Kudu/Scripts/selectNodeVersion.js:166\n    throw new Error('Unable to locate node.js installation directory at ' + nodejsDir);\n    ^\n\nError: Unable to locate node.js installation directory at /opt/nodejs\n    at Object.<anonymous> (/opt/Kudu/Scripts/selectNodeVersion.js:166:11)\n    at Module._compile (internal/modules/cjs/loader.js:108[5](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:5):14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:7[6](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:6):12)\n    at internal/main/run_main_module.js:1[7](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:8):[47](https://github.com/latitudegames/latitude-api-test/actions/runs/5762956206/job/15623785710#step:3:48)\n/opt/Kudu/Scripts/starter.sh bash deploy.sh
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = ZipDeploy. Extract zip.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed, Package deployment using ZIP Deploy failed. Refer logs for more details.
App Service Application URL: https://latitude-api-test.azurewebsites.net/
```
</details>

### Debug your Azure website remotely.
> it is recommanded that you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)
> we can take a look at what's going on.

Here's the [App Service](https://latitude-api-test.scm.azurewebsites.net/) where our reproduction repo is currently deployed.

### Mention any other details that might be useful.

I'm guessing we went wrong by trusting that the `kuduscript` generator was correct, as the blog post is 6 years old and the `kuduscript` generator repo hasn't been updated in 3 years. The instructions to download a deployment script from the Kudu portal in App Service also appear to be obsolete, since the Kudu portal doesn't have a Tools section. We're currently looking for a way to download the default Kudu script from Azure to get a correct starting point for the custom deployment script.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aawalton** [comment]
For my use case, I'm going to try to use only the standard build automation with customization through [Oryx](https://github.com/microsoft/Oryx/blob/main/doc/configuration.md) instead of using a custom deployment script. Without updates to the KuduScript repo, I don't see any way to use a custom deployment script for this use case.
