### ISSUE TITLE
Azure Deployment with DotCover "Access is denied"

### ISSUE THREAD

**Issue by devfunkd** [projectkudu/kudu#826]
I am looking to configure dotcover to run code coverage during deployment on Azure with the following line.

_UPDATE_ After a few days with the JetBrain team we managed to get it to run but now it seems the deployment stalls afterwards

 Command 'starter.cmd deploy.cmd' aborted due to no output and CPU activity for 600 seconds.  You may increase SCM_COMMAND_IDLE_TIMEOUT setting to solve the issue.
starter.cmd deploy.cmd

```
:::::::::::: RUNNING CODE COVERAGE ::::::::::::
JetBrains dotCover Console Runner v2.5.574.60. Copyright (c) 2009�2013 JetBrains s.r.o. All rights reserved.
 [JetBrains dotCover] Coverage session started [11/6/2013 8:42:44 PM]
Core Pdb Server v2.5.574.60 Copyright (C) 2012 JetBrains s.r.o. by Mikhail Pilin
Press Ctrl-C to terminate...
NUnit-Console version 2.6.3.13283
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.6407 ( Net 3.5 )
 ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
................................................................................................................
Tests run: 112, Errors: 0, Failures: 0, Inconclusive: 0, Time: 4.9889014 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
 [JetBrains dotCover] Coverage session finished [11/6/2013 8:42:55 PM]
[JetBrains dotCover] Coverage session finished but no snapshots were created. 
 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
An error has occurred during web site deployment.
   at MS.Win32.SafeNativeMethods.SafeNativeMethodsPrivate.IsWindowUnicode(HandleRef hWnd)
   at MS.Win32.ManagedWndProcTracker.GetDefWindowProcAddress(IntPtr hwnd)
   at MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
   at MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()


Here is the deploy.cmd script that I am using to call this.

IF NOT DEFINED DOTCOVER_PATH (
  SET DOTCOVER_PATH=%DEPLOYMENT_SOURCE%\BuildAndRelease\DotCover\dotcover.exe
)

    IF NOT DEFINED NUNIT_PATH (
      SET NUNIT_PATH=%DEPLOYMENT_SOURCE%\BuildAndRelease\NUnit\nunit-console.exe
    )

    IF NOT DEFINED TESTS_PATH (
      SET TESTS_PATH=%DEPLOYMENT_SOURCE%\Tests.Unit.Project\bin\Debug\Tests.Unit.Project.dll
    )

    :: 4. Running code coverage
    echo :::::::::::: RUNNING CODE COVERAGE ::::::::::::
    %DOTCOVER_PATH% analyse /TargetExecutable=%NUNIT_PATH% /TargetArguments=%TESTS_PATH% /TargetWorkingDir=%DEPLOYMENT_SOURCE%\Tests.Unit.Project\bin\Debug ^
     /Filters=+:module=*;class=*;function=*;-:module=*Tests* /ReportType=HTML /Output=%DEPLOYMENT_SOURCE%\Reports\Tests.Unit.Zenwire.html
    IF !ERRORLEVEL! NEQ 0 goto error
```

@gissues:{"order":88.4615384615384,"status":"backlog"}

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
