### ISSUE TITLE
WebJobs with Node (and node modules)

### ISSUE THREAD

**Issue by morgs32** [projectkudu/kudu#987]
I am bringing in all my NPM dependencies but it seems that makes the file paths too long.

Such as this is the error log. I even went into each node_module to bring their deeper node_modules into the topmost folder... and that didn't seem to work. I'd like to check that it's not because I'm compressing the files on a macintosh... I see some left overs in VS online indicating that azure puts node modules in a temp file and then converts them.

```
[01/23/2014 03:23:00 > 948219: SYS ERR ] Failed to copy job files: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Infrastructure.FileSystemHelpers.CopyDirectoryRecursive(IFileSystem fileSystem, String sourceDirPath, String destinationDirPath, Boolean overwrite)
   at Kudu.Core.Jobs.BaseJobRunner.CacheJobBinaries(IJobLogger logger)
[01/23/2014 03:23:00 > 948219: SYS ERR ] Failed to start job due to: System.InvalidOperationException: Missing working directory
   at Kudu.Core.Jobs.BaseJobRunner.InitializeJobInstance(JobBase job, IJobLogger logger)
   at Kudu.Core.Jobs.TriggeredJobRunner.StartJobRun(TriggeredJob triggeredJob)
```

**Comment by gamicklisafisher** [comment]
Long Path Tool is a best software to solve this issue. 5++ Rating. Long Path Tool is a best software
it is a free software. You can Try it
